org.facebook.crawler.FacebookDatabase Class Reference
Public Member Functions
FacebookDatabase (FacebookDBParams dbParams)
boolean createStatement ()
int executeQuery (String UserID, String[] arry, String[] GroupID, int Index)
String createQueryString (String SQLCommand, String tableName, String[] Values)
void initDatabaseConnection ()
void destroyDatabaseConnection ()
Private Attributes
Connection dbConn
String dbURL
Statement statement
ResultSet results
FacebookDBParams dbParams
Detailed Description
Definition at line 9 of file FacebookDatabase.java.
Constructor & Destructor Documentation
org.facebook.crawler.FacebookDatabase.FacebookDatabase (FacebookDBParams dbParams)
Definition at line 17 of file FacebookDatabase.java.
References org.facebook.crawler.FacebookDatabase.dbParams.
                                                        {
        this.dbParams = dbParams;
        
    }
Member Function Documentation
String org.facebook.crawler.FacebookDatabase.createQueryString (String SQLCommand, String tableName, String[] Values)
Definition at line 62 of file FacebookDatabase.java.
Referenced by org.facebook.crawler.FacebookDatabase.executeQuery().
                                                                                              {
        String queryString = "";
        String queryVals = "";
            if(tableName != null)
            if(SQLCommand.equalsIgnoreCase("INSERT")){
                queryString = queryString.concat("INSERT into " + tableName + " VALUES ('");
                System.out.println(Values.length + " Values");
                for(int i = 0; i < Values.length - 1; i++)
                    queryVals = queryVals.concat(Values[i] + "','");
                queryString = queryString.concat(queryVals + Values[Values.length - 1] + "')");
                System.out.println(queryString);
            }
        
        return queryString;
            
    }
boolean org.facebook.crawler.FacebookDatabase.createStatement ()
Definition at line 22 of file FacebookDatabase.java.
References org.facebook.crawler.FacebookDatabase.dbConn, and org.facebook.crawler.FacebookDatabase.statement.
Referenced by org.facebook.crawler.FacebookJsonParser.crawlJson().
                                    {
        
            try {
                this.statement = this.dbConn.createStatement();
            } catch (SQLException e) {
                // TODO Auto-generated catch block
                e.printStackTrace();
            }
        return true;
    }
void org.facebook.crawler.FacebookDatabase.destroyDatabaseConnection ()
Definition at line 96 of file FacebookDatabase.java.
References org.facebook.crawler.FacebookDatabase.dbConn.
Referenced by org.facebook.crawler.FacebookJsonParser.crawlJson().
                                           {
        try {
            
            dbConn.close();
            System.out.println("DB conn closed");
        
        } catch(Exception e){}
    }
int org.facebook.crawler.FacebookDatabase.executeQuery (String UserID, String[] arry, String[] GroupID, int Index)
Definition at line 33 of file FacebookDatabase.java.
References org.facebook.crawler.FacebookDatabase.createQueryString(), org.facebook.crawler.FacebookDatabase.results, and org.facebook.crawler.FacebookDatabase.statement.
Referenced by org.facebook.crawler.FacebookJsonParser.crawlUser().
                                                                                             {
        
        int count = 0;
        try {
            
            this.results = this.statement.executeQuery("SELECT DISTINCT id from user where
       id=" + UserID);
            
            while(results.next())
                count = count + 1;
            
            if(count == 0){
                /*count = this.statement.executeUpdate("INSERT into user VALUES
       ('"+arry[0]+"','"+arry[1]+"','"+arry[2]+"','"+arry[3]+"','"+arry[4]+
      "','"+arry[5]+"','"+arry[6]+"','"+arry[7]+"','"+arry[8]+"','"+arry[9]+"','"+arry[10]+"','"+arry[11]+"','"+arry[12]+"','"+
      arry[13]+"','"+arry[14]+"','"+arry[15]+"','"+arry[16]+"','"+arry[17]+"','"+arry[18]+"')");
                */
                
                count = this.statement.executeUpdate(this.
      createQueryString("INSERT" , "user" , arry));
            }
            
            if(Index != -1)
            count = this.statement.executeUpdate("INSERT into gruid (userid,groupid) VALUES ('" +
       UserID + "','" + GroupID[Index] + "')");
        } catch(Exception e){
            e.printStackTrace();
        }
        
        return count;
    }
void org.facebook.crawler.FacebookDatabase.initDatabaseConnection ()
Definition at line 79 of file FacebookDatabase.java.
References org.facebook.crawler.FacebookDatabase.dbConn, org.facebook.crawler.FacebookDatabase.dbParams, org.facebook.crawler.FacebookDatabase.dbURL, org.facebook.crawler.FacebookDBParams.getDBLink(), org.facebook.crawler.FacebookDBParams.getDBPass(), and org.facebook.crawler.FacebookDBParams.getDBUser().
Referenced by org.facebook.crawler.FacebookJsonParser.crawlJson().
                                         {
        
        try {
            
                this.dbURL = this.dbParams.getDBLink();
                Class.forName("com.mysql.jdbc.Driver").newInstance();
                this.dbConn = DriverManager.getConnection(this.dbURL, this.
      dbParams.getDBUser(), this.dbParams.getDBPass());
                System.out.println("DB conn established");
        } catch(Exception e) {
            System.err.println("Cannot connect to DB");
            System.err.println("Connection URL " + this.dbParams.
      getDBLink());
            System.err.println(e.getMessage());
        }
        
    }
Member Data Documentation
Connection org.facebook.crawler.FacebookDatabase.dbConn [private]
Definition at line 11 of file FacebookDatabase.java.
Referenced by org.facebook.crawler.FacebookDatabase.createStatement(), org.facebook.crawler.FacebookDatabase.destroyDatabaseConnection(), and org.facebook.crawler.FacebookDatabase.initDatabaseConnection().
FacebookDBParams org.facebook.crawler.FacebookDatabase.dbParams [private]
Definition at line 15 of file FacebookDatabase.java.
Referenced by org.facebook.crawler.FacebookDatabase.FacebookDatabase(), and org.facebook.crawler.FacebookDatabase.initDatabaseConnection().
String org.facebook.crawler.FacebookDatabase.dbURL [private]
Definition at line 12 of file FacebookDatabase.java.
Referenced by org.facebook.crawler.FacebookDatabase.initDatabaseConnection().
ResultSet org.facebook.crawler.FacebookDatabase.results [private]
Definition at line 14 of file FacebookDatabase.java.
Referenced by org.facebook.crawler.FacebookDatabase.executeQuery().
Statement org.facebook.crawler.FacebookDatabase.statement [private]
Definition at line 13 of file FacebookDatabase.java.
Referenced by org.facebook.crawler.FacebookDatabase.createStatement(), and org.facebook.crawler.FacebookDatabase.executeQuery().
The documentation for this class was generated from the following file:
org/facebook/crawler/FacebookDatabase.java