org.json.JSONObject Class Reference
Classes
class Null
Public Member Functions
JSONObject ()
JSONObject (JSONObject jo, String[] names)
JSONObject (JSONTokener x) throws JSONException
JSONObject (Map map)
JSONObject (Object bean)
JSONObject (Object object, String names[])
JSONObject (String source) throws JSONException
JSONObject (String baseName, Locale locale) throws JSONException
JSONObject accumulate (String key, Object value) throws JSONException
JSONObject append (String key, Object value) throws JSONException
Object get (String key) throws JSONException
boolean getBoolean (String key) throws JSONException
double getDouble (String key) throws JSONException
int getInt (String key) throws JSONException
JSONArray getJSONArray (String key) throws JSONException
JSONObject getJSONObject (String key) throws JSONException
long getLong (String key) throws JSONException
String getString (String key) throws JSONException
boolean has (String key)
JSONObject increment (String key) throws JSONException
boolean isNull (String key)
Iterator keys ()
Set keySet ()
int length ()
JSONArray names ()
Object opt (String key)
boolean optBoolean (String key)
boolean optBoolean (String key, boolean defaultValue)
double optDouble (String key)
double optDouble (String key, double defaultValue)
int optInt (String key)
int optInt (String key, int defaultValue)
JSONArray optJSONArray (String key)
JSONObject optJSONObject (String key)
long optLong (String key)
long optLong (String key, long defaultValue)
String optString (String key)
String optString (String key, String defaultValue)
JSONObject put (String key, boolean value) throws JSONException
JSONObject put (String key, Collection value) throws JSONException
JSONObject put (String key, double value) throws JSONException
JSONObject put (String key, int value) throws JSONException
JSONObject put (String key, long value) throws JSONException
JSONObject put (String key, Map value) throws JSONException
JSONObject put (String key, Object value) throws JSONException
JSONObject putOnce (String key, Object value) throws JSONException
JSONObject putOpt (String key, Object value) throws JSONException
Object remove (String key)
JSONArray toJSONArray (JSONArray names) throws JSONException
String toString ()
String toString (int indentFactor) throws JSONException
Writer write (Writer writer) throws JSONException
Static Public Member Functions
static String doubleToString (double d)
static String[] getNames (JSONObject jo)
static String[] getNames (Object object)
static String numberToString (Number number) throws JSONException
static String quote (String string)
static Writer quote (String string, Writer w) throws IOException
static Object stringToValue (String string)
static void testValidity (Object o) throws JSONException
static String valueToString (Object value) throws JSONException
static Object wrap (Object object)
Static Public Attributes
static final Object NULL = new Null()
Package Functions
Writer write (Writer writer, int indentFactor, int indent) throws JSONException
Static Package Functions
static final Writer writeValue (Writer writer, Object value, int indentFactor, int indent) throws JSONException, IOException
static final void indent (Writer writer, int indent) throws IOException
Private Member Functions
void populateMap (Object bean)
Private Attributes
final Map map
Static Private Attributes
static final int keyPoolSize = 100
static HashMap keyPool = new HashMap(keyPoolSize)
Detailed Description
A JSONObject is an unordered collection of name/value pairs. Its external form is a string wrapped in curly braces with colons between the names and values, and commas between the values and names. The internal form is an object having get and opt methods for accessing the values by name, and put methods for adding or replacing values by name. The values can be any of these types: Boolean, JSONArray, JSONObject, Number, String, or the JSONObject.NULL object. A JSONObject constructor can be used to convert an external form JSON text into an internal form whose values can be retrieved with the get and opt methods, or to convert values into a JSON text using the put and toString methods. A get method returns a value if one can be found, and throws an exception if one cannot be found. An opt method returns a default value instead of throwing an exception, and so is useful for obtaining optional values.
The generic get() and opt() methods return an object, which you can cast or query for type. There are also typed get and opt methods that do type checking and type coercion for you. The opt methods differ from the get methods in that they do not throw. Instead, they return a specified value, such as null.
The put methods add or replace values in an object. For example,
myString = new JSONObject()
        .put("JSON", "Hello, World!").toString();
produces the string {`JSON`: `Hello, World`}.
The texts produced by the toString methods strictly conform to the JSON syntax rules. The constructors are more forgiving in the texts they will accept:
An extra ,
(comma)
may appear just before the closing brace.
Strings may be quoted with '
(single quote)
.
Strings do not need to be quoted at all if they do not begin with a quote or single quote, and if they do not contain leading or trailing spaces, and if they do not contain any of these characters: { } [ ] / \ : , # and if they do not look like numbers and if they are not the reserved words true, false, or null.
Author
JSON.org
Version
2013-04-18
Definition at line 95 of file JSONObject.java.
Constructor & Destructor Documentation
org.json.JSONObject.JSONObject ()
Construct an empty JSONObject.
Definition at line 164 of file JSONObject.java.
References org.json.JSONObject.map.
Referenced by org.json.JSONObject.JSONObject(), org.json.JSONObject.optJSONObject(), org.json.JSONObject.put(), org.json.JSONObject.valueToString(), org.json.JSONObject.wrap(), and org.json.JSONObject.writeValue().
                        {
        this.map = new HashMap();
    }
org.json.JSONObject.JSONObject (JSONObject jo, String[] names)
Construct a JSONObject from a subset of another JSONObject. An array of strings is used to identify the keys that should be copied. Missing keys are ignored.
Parameters
jo A JSONObject.
names An array of strings.
Exceptions
JSONException
JSONException If a value is a non-finite number or if a name is duplicated.
Definition at line 182 of file JSONObject.java.
References org.json.JSONObject.opt(), and org.json.JSONObject.putOnce().
                                                     {
        this();
        for (int i = 0; i < names.length; i += 1) {
            try {
                this.putOnce(names[i], jo.opt(names[i]));
            } catch (Exception ignore) {
            }
        }
    }
org.json.JSONObject.JSONObject (JSONTokener x) throws JSONException
Construct a JSONObject from a JSONTokener.
Parameters
x A JSONTokener object containing the source string.
Exceptions
JSONException If there is a syntax error in the source string or a duplicated key.
Definition at line 201 of file JSONObject.java.
References org.json.JSONObject.putOnce().
                                                          {
        this();
        char c;
        String key;
        if (x.nextClean() != '{') {
            throw x.syntaxError("A JSONObject text must begin with '{'");
        }
        for (;;) {
            c = x.nextClean();
            switch (c) {
            case 0:
                throw x.syntaxError("A JSONObject text must end with '}'");
            case '}':
                return;
            default:
                x.back();
                key = x.nextValue().toString();
            }
// The key is followed by ':'.
            c = x.nextClean();
            if (c != ':') {
                throw x.syntaxError("Expected a ':' after a key");
            }
            this.putOnce(key, x.nextValue());
// Pairs are separated by ','.
            switch (x.nextClean()) {
            case ';':
            case ',':
                if (x.nextClean() == '}') {
                    return;
                }
                x.back();
                break;
            case '}':
                return;
            default:
                throw x.syntaxError("Expected a ',' or '}'");
            }
        }
    }
org.json.JSONObject.JSONObject (Map map)
Construct a JSONObject from a Map.
Parameters
map A map object that can be used to initialize the contents of the JSONObject.
Exceptions
JSONException
Definition at line 255 of file JSONObject.java.
References org.json.JSONObject.wrap().
                               {
        this.map = new HashMap();
        if (map != null) {
            Iterator i = map.entrySet().iterator();
            while (i.hasNext()) {
                Map.Entry e = (Map.Entry) i.next();
                Object value = e.getValue();
                if (value != null) {
                    this.map.put(e.getKey(), wrap(value));
                }
            }
        }
    }
org.json.JSONObject.JSONObject (Object bean)
Construct a JSONObject from an Object using bean getters. It reflects on all of the public methods of the object. For each of the methods with no parameters and a name starting with `get` or `is` followed by an uppercase letter, the method is invoked, and a key and the value returned from the getter method are put into the new JSONObject.
The key is formed by removing the `get` or `is` prefix. If the second remaining character is not upper case, then the first character is converted to lower case.
For example, if an object has a method named `getName`, and if the result of calling object.getName() is `Larry Fine`, then the JSONObject will contain `name`: `Larry Fine`.
Parameters
bean An object that has getter methods that should be used to make a JSONObject.
Definition at line 290 of file JSONObject.java.
References org.json.JSONObject.populateMap().
                                   {
        this();
        this.populateMap(bean);
    }
org.json.JSONObject.JSONObject (Object object, String names[])
Construct a JSONObject from an Object, using reflection to find the public members. The resulting JSONObject's keys will be the strings from the names array, and the values will be the field values associated with those keys in the object. If a key is not found or not visible, then it will not be copied into the new JSONObject.
Parameters
object An object that has fields that should be used to make a JSONObject.
names An array of strings, the names of the fields to be obtained from the object.
Definition at line 309 of file JSONObject.java.
References org.json.JSONObject.putOpt().
                                                     {
        this();
        Class c = object.getClass();
        for (int i = 0; i < names.length; i += 1) {
            String name = names[i];
            try {
                this.putOpt(name, c.getField(name).get(object));
            } catch (Exception ignore) {
            }
        }
    }
org.json.JSONObject.JSONObject (String source) throws JSONException
Construct a JSONObject from a source JSON text string. This is the most commonly used JSONObject constructor.
Parameters
source A string beginning with {
(left brace)
and ending with }
(right brace)
.
Exceptions
JSONException If there is a syntax error in the source string or a duplicated key.
Definition at line 333 of file JSONObject.java.
                                                          {
        this(new JSONTokener(source));
    }
org.json.JSONObject.JSONObject (String baseName, Locale locale) throws JSONException
Construct a JSONObject from a ResourceBundle.
Parameters
baseName The ResourceBundle base name.
locale The Locale to load the ResourceBundle for.
Exceptions
JSONException If any JSONExceptions are detected.
Definition at line 347 of file JSONObject.java.
References org.json.JSONObject.JSONObject(), org.json.JSONObject.keys(), org.json.JSONObject.optJSONObject(), and org.json.JSONObject.put().
                                                                           {
        this();
        ResourceBundle bundle = ResourceBundle.getBundle(baseName, locale,
                Thread.currentThread().getContextClassLoader());
// Iterate through the keys in the bundle.
        Enumeration keys = bundle.getKeys();
        while (keys.hasMoreElements()) {
            Object key = keys.nextElement();
            if (key instanceof String) {
// Go through the path, ensuring that there is a nested JSONObject for each
// segment except the last. Add the value using the last segment's name into
// the deepest nested JSONObject.
                String[] path = ((String) key).split("\\.");
                int last = path.length - 1;
                JSONObject target = this;
                for (int i = 0; i < last; i += 1) {
                    String segment = path[i];
                    JSONObject nextTarget = target.optJSONObject(segment);
                    if (nextTarget == null) {
                        nextTarget = new JSONObject();
                        target.put(segment, nextTarget);
                    }
                    target = nextTarget;
                }
                target.put(path[last], bundle.getString((String) key));
            }
        }
    }
Member Function Documentation
JSONObject org.json.JSONObject.accumulate (String key, Object value) throws JSONException
Accumulate values under a key. It is similar to the put method except that if there is already an object stored under the key then a JSONArray is stored under the key to hold all of the accumulated values. If there is already a JSONArray, then the new value is appended to it. In contrast, the put method replaces the previous value.
If only one value is accumulated that is not a JSONArray, then the result will be the same as using put. But if multiple values are accumulated, then the result will be like append.
Parameters
key A key string.
value An object to be accumulated under the key.
Returns
this.
Exceptions
JSONException If the value is an invalid number or if the key is null.
Definition at line 399 of file JSONObject.java.
References org.json.JSONObject.opt(), org.json.JSONObject.put(), and org.json.JSONObject.testValidity().
Referenced by org.json.JSONML.parse(), and org.json.XML.parse().
                                                                                {
        testValidity(value);
        Object object = this.opt(key);
        if (object == null) {
            this.put(key,
                    value instanceof JSONArray ? new JSONArray().put(value)
                            : value);
        } else if (object instanceof JSONArray) {
            ((JSONArray) object).put(value);
        } else {
            this.put(key, new JSONArray().put(object).put(value));
        }
        return this;
    }
JSONObject org.json.JSONObject.append (String key, Object value) throws JSONException
Append values to the array under a key. If the key does not exist in the JSONObject, then the key is put in the JSONObject with its value being a JSONArray containing the value parameter. If the key was already associated with a JSONArray, then the value parameter is appended to it.
Parameters
key A key string.
value An object to be accumulated under the key.
Returns
this.
Exceptions
JSONException If the key is null or if the current value associated with the key is not a JSONArray.
Definition at line 429 of file JSONObject.java.
References org.json.JSONObject.opt(), org.json.JSONObject.put(), and org.json.JSONObject.testValidity().
Referenced by org.json.CDL.toString(), and org.json.XML.toString().
                                                                            {
        testValidity(value);
        Object object = this.opt(key);
        if (object == null) {
            this.put(key, new JSONArray().put(value));
        } else if (object instanceof JSONArray) {
            this.put(key, ((JSONArray) object).put(value));
        } else {
            throw new JSONException("JSONObject[" + key
                    + "] is not a JSONArray.");
        }
        return this;
    }
static String org.json.JSONObject.doubleToString (double d) [static]
Produce a string from a double. The string `null` will be returned if the number is not finite.
Parameters
d A double.
Returns
A String.
Definition at line 451 of file JSONObject.java.
References org.json.JSONObject.length().
                                                  {
        if (Double.isInfinite(d) || Double.isNaN(d)) {
            return "null";
        }
// Shave off trailing zeros and decimal point, if possible.
        String string = Double.toString(d);
        if (string.indexOf('.') > 0 && string.indexOf('e') < 0
                && string.indexOf('E') < 0) {
            while (string.endsWith("0")) {
                string = string.substring(0, string.length() - 1);
            }
            if (string.endsWith(".")) {
                string = string.substring(0, string.length() - 1);
            }
        }
        return string;
    }
Object org.json.JSONObject.get (String key) throws JSONException
Get the value object associated with a key.
Parameters
key A key string.
Returns
The object associated with the key.
Exceptions
JSONException if the key is not found.
Definition at line 480 of file JSONObject.java.
References org.json.JSONObject.opt(), and org.json.JSONObject.quote().
                                                       {
        if (key == null) {
            throw new JSONException("Null key.");
        }
        Object object = this.opt(key);
        if (object == null) {
            throw new JSONException("JSONObject[" + quote(key) + "] not found.");
        }
        return object;
    }
boolean org.json.JSONObject.getBoolean (String key) throws JSONException
Get the boolean value associated with a key.
Parameters
key A key string.
Returns
The truth.
Exceptions
JSONException if the value is not a Boolean or the String `true` or `false`.
Definition at line 501 of file JSONObject.java.
References org.json.JSONObject.quote().
Referenced by org.json.JSONObject.optBoolean().
                                                               {
        Object object = this.get(key);
        if (object.equals(Boolean.FALSE)
                || (object instanceof String && ((String) object)
                        .equalsIgnoreCase("false"))) {
            return false;
        } else if (object.equals(Boolean.TRUE)
                || (object instanceof String && ((String) object)
                        .equalsIgnoreCase("true"))) {
            return true;
        }
        throw new JSONException("JSONObject[" + quote(key)
                + "] is not a Boolean.");
    }
double org.json.JSONObject.getDouble (String key) throws JSONException
Get the double value associated with a key.
Parameters
key A key string.
Returns
The numeric value.
Exceptions
JSONException if the key is not found or if the value is not a Number object and cannot be converted to a number.
Definition at line 526 of file JSONObject.java.
References org.json.JSONObject.quote().
Referenced by org.json.JSONObject.optDouble().
                                                             {
        Object object = this.get(key);
        try {
            return object instanceof Number ? ((Number) object).doubleValue()
                    : Double.parseDouble((String) object);
        } catch (Exception e) {
            throw new JSONException("JSONObject[" + quote(key)
                    + "] is not a number.");
        }
    }
int org.json.JSONObject.getInt (String key) throws JSONException
Get the int value associated with a key.
Parameters
key A key string.
Returns
The integer value.
Exceptions
JSONException if the key is not found or if the value cannot be converted to an integer.
Definition at line 547 of file JSONObject.java.
References org.json.JSONObject.quote().
Referenced by org.json.JSONObject.optInt().
                                                       {
        Object object = this.get(key);
        try {
            return object instanceof Number ? ((Number) object).intValue()
                    : Integer.parseInt((String) object);
        } catch (Exception e) {
            throw new JSONException("JSONObject[" + quote(key)
                    + "] is not an int.");
        }
    }
JSONArray org.json.JSONObject.getJSONArray (String key) throws JSONException
Get the JSONArray value associated with a key.
Parameters
key A key string.
Returns
A JSONArray which is the value.
Exceptions
JSONException if the key is not found or if the value is not a JSONArray.
Definition at line 567 of file JSONObject.java.
References org.json.JSONObject.quote().
Referenced by org.facebook.crawler.FacebookJsonParser.crawlGroup(), org.facebook.crawler.FacebookJsonParser.crawlUser(), and JsonReader.main().
                                                                   {
        Object object = this.get(key);
        if (object instanceof JSONArray) {
            return (JSONArray) object;
        }
        throw new JSONException("JSONObject[" + quote(key)
                + "] is not a JSONArray.");
    }
JSONObject org.json.JSONObject.getJSONObject (String key) throws JSONException
Get the JSONObject value associated with a key.
Parameters
key A key string.
Returns
A JSONObject which is the value.
Exceptions
JSONException if the key is not found or if the value is not a JSONObject.
Definition at line 585 of file JSONObject.java.
References org.json.JSONObject.quote().
Referenced by org.facebook.crawler.FacebookJsonParser.crawlUser(), and JsonReader.main().
                                                                     {
        Object object = this.get(key);
        if (object instanceof JSONObject) {
            return (JSONObject) object;
        }
        throw new JSONException("JSONObject[" + quote(key)
                + "] is not a JSONObject.");
    }
long org.json.JSONObject.getLong (String key) throws JSONException
Get the long value associated with a key.
Parameters
key A key string.
Returns
The long value.
Exceptions
JSONException if the key is not found or if the value cannot be converted to a long.
Definition at line 604 of file JSONObject.java.
References org.json.JSONObject.quote().
Referenced by org.json.JSONObject.optLong().
                                                         {
        Object object = this.get(key);
        try {
            return object instanceof Number ? ((Number) object).longValue()
                    : Long.parseLong((String) object);
        } catch (Exception e) {
            throw new JSONException("JSONObject[" + quote(key)
                    + "] is not a long.");
        }
    }
static String [] org.json.JSONObject.getNames (JSONObject jo) [static]
Get an array of field names from a JSONObject.
Returns
An array of field names, or null if there are no names.
Definition at line 620 of file JSONObject.java.
References org.json.JSONObject.keys(), org.json.JSONObject.length(), and org.json.JSONObject.names().
Referenced by org.facebook.crawler.FacebookJsonParser.crawlUser(), and JsonReader.main().
                                                   {
        int length = jo.length();
        if (length == 0) {
            return null;
        }
        Iterator iterator = jo.keys();
        String[] names = new String[length];
        int i = 0;
        while (iterator.hasNext()) {
            names[i] = (String) iterator.next();
            i += 1;
        }
        return names;
    }
static String [] org.json.JSONObject.getNames (Object object) [static]
Get an array of field names from an Object.
Returns
An array of field names, or null if there are no names.
Definition at line 640 of file JSONObject.java.
References org.json.JSONObject.length(), and org.json.JSONObject.names().
                                                   {
        if (object == null) {
            return null;
        }
        Class klass = object.getClass();
        Field[] fields = klass.getFields();
        int length = fields.length;
        if (length == 0) {
            return null;
        }
        String[] names = new String[length];
        for (int i = 0; i < length; i += 1) {
            names[i] = fields[i].getName();
        }
        return names;
    }
String org.json.JSONObject.getString (String key) throws JSONException
Get the string associated with a key.
Parameters
key A key string.
Returns
A string which is the value.
Exceptions
JSONException if there is no string value for the key.
Definition at line 666 of file JSONObject.java.
References org.json.JSONObject.quote().
Referenced by org.facebook.crawler.FacebookJsonParser.crawlUser(), and JsonReader.main().
                                                             {
        Object object = this.get(key);
        if (object instanceof String) {
            return (String) object;
        }
        throw new JSONException("JSONObject[" + quote(key) + "] not a string.");
    }
boolean org.json.JSONObject.has (String key)
Determine if the JSONObject contains a specific key.
Parameters
key A key string.
Returns
true if the key exists in the JSONObject.
Definition at line 681 of file JSONObject.java.
References org.json.JSONObject.map.
                                   {
        return this.map.containsKey(key);
    }
JSONObject org.json.JSONObject.increment (String key) throws JSONException
Increment a property of a JSONObject. If there is no such property, create one with a value of 1. If there is such a property, and if it is an Integer, Long, Double, or Float, then add one to it.
Parameters
key A key string.
Returns
this.
Exceptions
JSONException If there is already a property with this name that is not an Integer, Long, Double, or Float.
Definition at line 697 of file JSONObject.java.
References org.json.JSONObject.opt(), org.json.JSONObject.put(), and org.json.JSONObject.quote().
                                                                 {
        Object value = this.opt(key);
        if (value == null) {
            this.put(key, 1);
        } else if (value instanceof Integer) {
            this.put(key, ((Integer) value).intValue() + 1);
        } else if (value instanceof Long) {
            this.put(key, ((Long) value).longValue() + 1);
        } else if (value instanceof Double) {
            this.put(key, ((Double) value).doubleValue() + 1);
        } else if (value instanceof Float) {
            this.put(key, ((Float) value).floatValue() + 1);
        } else {
            throw new JSONException("Unable to increment [" + quote(key) + "].");
        }
        return this;
    }
static final void org.json.JSONObject.indent (Writer writer, int indent) throws IOException [static], [package]
Definition at line 1602 of file JSONObject.java.
Referenced by org.json.JSONArray.write(), org.json.JSONObject.write(), and org.json.JSONObject.writeValue().
                                                                           {
        for (int i = 0; i < indent; i += 1) {
            writer.write(' ');
        }
    }
boolean org.json.JSONObject.isNull (String key)
Determine if the value associated with the key is null or if there is no value.
Parameters
key A key string.
Returns
true if there is no value associated with the key or if the value is the JSONObject.NULL object.
Definition at line 724 of file JSONObject.java.
References org.json.JSONObject.NULL, and org.json.JSONObject.opt().
                                      {
        return JSONObject.NULL.equals(this.opt(key));
    }
Iterator org.json.JSONObject.keys ()
Get an enumeration of the keys of the JSONObject.
Returns
An iterator of the keys.
Definition at line 733 of file JSONObject.java.
References org.json.JSONObject.keySet().
Referenced by org.json.JSONObject.getNames(), org.json.JSONObject.JSONObject(), org.json.JSONObject.names(), org.json.JSONML.toString(), org.json.XML.toString(), and org.json.JSONObject.write().
                           {
        return this.keySet().iterator();
    }
Set org.json.JSONObject.keySet ()
Get a set of keys of the JSONObject.
Returns
A keySet.
Definition at line 742 of file JSONObject.java.
References org.json.JSONObject.map.
Referenced by org.json.JSONObject.keys().
                        {
        return this.map.keySet();
    }
int org.json.JSONObject.length ()
Get the number of keys stored in the JSONObject.
Returns
The number of keys in the JSONObject.
Definition at line 751 of file JSONObject.java.
References org.json.JSONObject.map.
Referenced by org.json.JSONObject.doubleToString(), org.json.JSONObject.getNames(), org.json.JSONObject.numberToString(), org.json.JSONML.parse(), org.json.XML.parse(), org.json.JSONObject.quote(), and org.json.JSONObject.write().
                        {
        return this.map.size();
    }
JSONArray org.json.JSONObject.names ()
Produce a JSONArray containing the names of the elements of this JSONObject.
Returns
A JSONArray containing the key strings, or null if the JSONObject is empty.
Definition at line 762 of file JSONObject.java.
References org.json.JSONObject.keys(), org.json.JSONArray.length(), and org.json.JSONArray.put().
Referenced by org.facebook.crawler.FacebookJsonParser.crawlUser(), org.json.JSONObject.getNames(), JsonReader.main(), org.json.JSONObject.toJSONArray(), and org.json.CDL.toString().
                             {
        JSONArray ja = new JSONArray();
        Iterator keys = this.keys();
        while (keys.hasNext()) {
            ja.put(keys.next());
        }
        return ja.length() == 0 ? null : ja;
    }
static String org.json.JSONObject.numberToString (Number number) throws JSONException [static]
Produce a string from a Number.
Parameters
number A Number
Returns
A String.
Exceptions
JSONException If n is a non-finite number.
Definition at line 780 of file JSONObject.java.
References org.json.JSONObject.length(), and org.json.JSONObject.testValidity().
Referenced by org.json.JSONObject.valueToString(), and org.json.JSONObject.writeValue().
                                                                            {
        if (number == null) {
            throw new JSONException("Null pointer");
        }
        testValidity(number);
// Shave off trailing zeros and decimal point, if possible.
        String string = number.toString();
        if (string.indexOf('.') > 0 && string.indexOf('e') < 0
                && string.indexOf('E') < 0) {
            while (string.endsWith("0")) {
                string = string.substring(0, string.length() - 1);
            }
            if (string.endsWith(".")) {
                string = string.substring(0, string.length() - 1);
            }
        }
        return string;
    }
Object org.json.JSONObject.opt (String key)
Get an optional value associated with a key.
Parameters
key A key string.
Returns
An object which is the value, or null if there is no value.
Definition at line 808 of file JSONObject.java.
References org.json.JSONObject.map.
Referenced by org.json.JSONObject.accumulate(), org.json.JSONObject.append(), org.json.JSONObject.get(), org.json.JSONObject.increment(), org.json.JSONObject.isNull(), org.json.JSONObject.JSONObject(), org.json.JSONObject.optJSONArray(), org.json.JSONObject.optJSONObject(), org.json.JSONObject.optString(), org.json.XML.parse(), org.json.JSONObject.putOnce(), org.json.JSONObject.toJSONArray(), and org.json.XML.toString().
                                  {
        return key == null ? null : this.map.get(key);
    }
boolean org.json.JSONObject.optBoolean (String key)
Get an optional boolean associated with a key. It returns false if there is no such key, or if the value is not Boolean.TRUE or the String `true`.
Parameters
key A key string.
Returns
The truth.
Definition at line 820 of file JSONObject.java.
                                          {
        return this.optBoolean(key, false);
    }
boolean org.json.JSONObject.optBoolean (String key, boolean defaultValue)
Get an optional boolean associated with a key. It returns the defaultValue if there is no such key, or if it is not a Boolean or the String `true` or `false` (case insensitive).
Parameters
key A key string.
defaultValue The default.
Returns
The truth.
Definition at line 835 of file JSONObject.java.
References org.json.JSONObject.getBoolean().
                                                                {
        try {
            return this.getBoolean(key);
        } catch (Exception e) {
            return defaultValue;
        }
    }
double org.json.JSONObject.optDouble (String key)
Get an optional double associated with a key, or NaN if there is no such key or if its value is not a number. If the value is a string, an attempt will be made to evaluate it as a number.
Parameters
key A string which is the key.
Returns
An object which is the value.
Definition at line 852 of file JSONObject.java.
                                        {
        return this.optDouble(key, Double.NaN);
    }
double org.json.JSONObject.optDouble (String key, double defaultValue)
Get an optional double associated with a key, or the defaultValue if there is no such key or if its value is not a number. If the value is a string, an attempt will be made to evaluate it as a number.
Parameters
key A key string.
defaultValue The default.
Returns
An object which is the value.
Definition at line 867 of file JSONObject.java.
References org.json.JSONObject.getDouble().
                                                             {
        try {
            return this.getDouble(key);
        } catch (Exception e) {
            return defaultValue;
        }
    }
int org.json.JSONObject.optInt (String key)
Get an optional int value associated with a key, or zero if there is no such key or if the value is not a number. If the value is a string, an attempt will be made to evaluate it as a number.
Parameters
key A key string.
Returns
An object which is the value.
Definition at line 884 of file JSONObject.java.
                                  {
        return this.optInt(key, 0);
    }
int org.json.JSONObject.optInt (String key, int defaultValue)
Get an optional int value associated with a key, or the default if there is no such key or if the value is not a number. If the value is a string, an attempt will be made to evaluate it as a number.
Parameters
key A key string.
defaultValue The default.
Returns
An object which is the value.
Definition at line 899 of file JSONObject.java.
References org.json.JSONObject.getInt().
                                                    {
        try {
            return this.getInt(key);
        } catch (Exception e) {
            return defaultValue;
        }
    }
JSONArray org.json.JSONObject.optJSONArray (String key)
Get an optional JSONArray associated with a key. It returns null if there is no such key, or if its value is not a JSONArray.
Parameters
key A key string.
Returns
A JSONArray which is the value.
Definition at line 915 of file JSONObject.java.
References org.json.JSONObject.opt().
                                              {
        Object o = this.opt(key);
        return o instanceof JSONArray ? (JSONArray) o : null;
    }
JSONObject org.json.JSONObject.optJSONObject (String key)
Get an optional JSONObject associated with a key. It returns null if there is no such key, or if its value is not a JSONObject.
Parameters
key A key string.
Returns
A JSONObject which is the value.
Definition at line 928 of file JSONObject.java.
References org.json.JSONObject.JSONObject(), and org.json.JSONObject.opt().
Referenced by org.json.JSONObject.JSONObject(), and org.json.CDL.toString().
                                                {
        Object object = this.opt(key);
        return object instanceof JSONObject ? (JSONObject) object : null;
    }
long org.json.JSONObject.optLong (String key)
Get an optional long value associated with a key, or zero if there is no such key or if the value is not a number. If the value is a string, an attempt will be made to evaluate it as a number.
Parameters
key A key string.
Returns
An object which is the value.
Definition at line 942 of file JSONObject.java.
                                    {
        return this.optLong(key, 0);
    }
long org.json.JSONObject.optLong (String key, long defaultValue)
Get an optional long value associated with a key, or the default if there is no such key or if the value is not a number. If the value is a string, an attempt will be made to evaluate it as a number.
Parameters
key A key string.
defaultValue The default.
Returns
An object which is the value.
Definition at line 957 of file JSONObject.java.
References org.json.JSONObject.getLong().
                                                       {
        try {
            return this.getLong(key);
        } catch (Exception e) {
            return defaultValue;
        }
    }
String org.json.JSONObject.optString (String key)
Get an optional string associated with a key. It returns an empty string if there is no such key. If the value is not a string and is not null, then it is converted to a string.
Parameters
key A key string.
Returns
A string which is the value.
Definition at line 974 of file JSONObject.java.
Referenced by org.json.JSONML.toString().
                                        {
        return this.optString(key, "");
    }
String org.json.JSONObject.optString (String key, String defaultValue)
Get an optional string associated with a key. It returns the defaultValue if there is no such key.
Parameters
key A key string.
defaultValue The default.
Returns
A string which is the value.
Definition at line 988 of file JSONObject.java.
References org.json.JSONObject.NULL, and org.json.JSONObject.opt().
                                                             {
        Object object = this.opt(key);
        return NULL.equals(object) ? defaultValue : object.toString();
    }
void org.json.JSONObject.populateMap (Object bean) [private]
Definition at line 993 of file JSONObject.java.
References org.json.JSONObject.map, and org.json.JSONObject.wrap().
Referenced by org.json.JSONObject.JSONObject().
                                          {
        Class klass = bean.getClass();
// If klass is a System class then set includeSuperClass to false.
        boolean includeSuperClass = klass.getClassLoader() != null;
        Method[] methods = includeSuperClass ? klass.getMethods() : klass
                .getDeclaredMethods();
        for (int i = 0; i < methods.length; i += 1) {
            try {
                Method method = methods[i];
                if (Modifier.isPublic(method.getModifiers())) {
                    String name = method.getName();
                    String key = "";
                    if (name.startsWith("get")) {
                        if ("getClass".equals(name)
                                || "getDeclaringClass".equals(name)) {
                            key = "";
                        } else {
                            key = name.substring(3);
                        }
                    } else if (name.startsWith("is")) {
                        key = name.substring(2);
                    }
                    if (key.length() > 0
                            && Character.isUpperCase(key.charAt(0))
                            && method.getParameterTypes().length == 0) {
                        if (key.length() == 1) {
                            key = key.toLowerCase();
                        } else if (!Character.isUpperCase(key.charAt(1))) {
                            key = key.substring(0, 1).toLowerCase()
                                    + key.substring(1);
                        }
                        Object result = method.invoke(bean, (Object[]) null);
                        if (result != null) {
                            this.map.put(key, wrap(result));
                        }
                    }
                }
            } catch (Exception ignore) {
            }
        }
    }
JSONObject org.json.JSONObject.put (String key, boolean value) throws JSONException
Put a key/boolean pair in the JSONObject.
Parameters
key A key string.
value A boolean which is the value.
Returns
this.
Exceptions
JSONException If the key is null.
Definition at line 1050 of file JSONObject.java.
Referenced by org.json.JSONObject.accumulate(), org.json.JSONObject.append(), org.facebook.crawler.FacebookJsonParser.crawlUsers(), org.json.JSONObject.increment(), org.json.JSONObject.JSONObject(), org.json.JSONML.parse(), org.json.JSONObject.put(), org.json.JSONObject.putOnce(), org.json.JSONObject.putOpt(), org.json.Property.toJSONObject(), org.json.CookieList.toJSONObject(), org.json.HTTP.toJSONObject(), org.json.Cookie.toJSONObject(), and org.json.JSONArray.toJSONObject().
                                                                          {
        this.put(key, value ? Boolean.TRUE : Boolean.FALSE);
        return this;
    }
JSONObject org.json.JSONObject.put (String key, Collection value) throws JSONException
Put a key/value pair in the JSONObject, where the value will be a JSONArray which is produced from a Collection.
Parameters
key A key string.
value A Collection value.
Returns
this.
Exceptions
JSONException
Definition at line 1066 of file JSONObject.java.
References org.json.JSONObject.put().
                                                                             {
        this.put(key, new JSONArray(value));
        return this;
    }
JSONObject org.json.JSONObject.put (String key, double value) throws JSONException
Put a key/double pair in the JSONObject.
Parameters
key A key string.
value A double which is the value.
Returns
this.
Exceptions
JSONException If the key is null or if the number is invalid.
Definition at line 1082 of file JSONObject.java.
References org.json.JSONObject.put().
                                                                         {
        this.put(key, new Double(value));
        return this;
    }
JSONObject org.json.JSONObject.put (String key, int value) throws JSONException
Put a key/int pair in the JSONObject.
Parameters
key A key string.
value An int which is the value.
Returns
this.
Exceptions
JSONException If the key is null.
Definition at line 1098 of file JSONObject.java.
References org.json.JSONObject.put().
                                                                      {
        this.put(key, new Integer(value));
        return this;
    }
JSONObject org.json.JSONObject.put (String key, long value) throws JSONException
Put a key/long pair in the JSONObject.
Parameters
key A key string.
value A long which is the value.
Returns
this.
Exceptions
JSONException If the key is null.
Definition at line 1114 of file JSONObject.java.
References org.json.JSONObject.put().
                                                                       {
        this.put(key, new Long(value));
        return this;
    }
JSONObject org.json.JSONObject.put (String key, Map value) throws JSONException
Put a key/value pair in the JSONObject, where the value will be a JSONObject which is produced from a Map.
Parameters
key A key string.
value A Map value.
Returns
this.
Exceptions
JSONException
Definition at line 1130 of file JSONObject.java.
References org.json.JSONObject.JSONObject(), and org.json.JSONObject.put().
                                                                      {
        this.put(key, new JSONObject(value));
        return this;
    }
JSONObject org.json.JSONObject.put (String key, Object value) throws JSONException
Put a key/value pair in the JSONObject. If the value is null, then the key will be removed from the JSONObject if it is present.
Parameters
key A key string.
value An object which is the value. It should be of one of these types: Boolean, Double, Integer, JSONArray, JSONObject, Long, String, or the JSONObject.NULL object.
Returns
this.
Exceptions
JSONException If the value is non-finite number or if the key is null.
Definition at line 1149 of file JSONObject.java.
References org.json.JSONObject.keyPool, org.json.JSONObject.keyPoolSize, org.json.JSONObject.map, and org.json.JSONObject.testValidity().
                                                                         {
        String pooled;
        if (key == null) {
            throw new NullPointerException("Null key.");
        }
        if (value != null) {
            testValidity(value);
            pooled = (String) keyPool.get(key);
            if (pooled == null) {
                if (keyPool.size() >= keyPoolSize) {
                    keyPool = new HashMap(keyPoolSize);
                }
                keyPool.put(key, key);
            } else {
                key = pooled;
            }
            this.map.put(key, value);
        } else {
            this.remove(key);
        }
        return this;
    }
JSONObject org.json.JSONObject.putOnce (String key, Object value) throws JSONException
Put a key/value pair in the JSONObject, but only if the key and the value are both non-null, and only if there is not already a member with that name.
Parameters
key
value
Returns
his.
Exceptions
JSONException if the key is a duplicate
Definition at line 1183 of file JSONObject.java.
References org.json.JSONObject.opt(), and org.json.JSONObject.put().
Referenced by org.json.JSONObject.JSONObject(), and org.json.JSONWriter.key().
                                                                             {
        if (key != null && value != null) {
            if (this.opt(key) != null) {
                throw new JSONException("Duplicate key \"" + key + "\"");
            }
            this.put(key, value);
        }
        return this;
    }
JSONObject org.json.JSONObject.putOpt (String key, Object value) throws JSONException
Put a key/value pair in the JSONObject, but only if the key and the value are both non-null.
Parameters
key A key string.
value An object which is the value. It should be of one of these types: Boolean, Double, Integer, JSONArray, JSONObject, Long, String, or the JSONObject.NULL object.
Returns
this.
Exceptions
JSONException If the value is a non-finite number.
Definition at line 1207 of file JSONObject.java.
References org.json.JSONObject.put().
Referenced by org.json.JSONObject.JSONObject().
                                                                            {
        if (key != null && value != null) {
            this.put(key, value);
        }
        return this;
    }
static String org.json.JSONObject.quote (String string) [static]
Produce a string in double quotes with backslash sequences in all the right places. A backslash will be inserted within </, producing <\/, allowing JSON text to be delivered in HTML. In JSON text, a string cannot contain a control character or an unescaped quote or backslash.
Parameters
string A String
Returns
A String correctly formatted for insertion in a JSON text.
Definition at line 1224 of file JSONObject.java.
Referenced by org.json.JSONObject.get(), org.json.JSONObject.getBoolean(), org.json.JSONObject.getDouble(), org.json.JSONObject.getInt(), org.json.JSONObject.getJSONArray(), org.json.JSONObject.getJSONObject(), org.json.JSONObject.getLong(), org.json.JSONObject.getString(), org.json.JSONObject.increment(), org.json.JSONWriter.key(), org.json.JSONObject.valueToString(), org.json.JSONObject.write(), and org.json.JSONObject.writeValue().
                                              {
        StringWriter sw = new StringWriter();
        synchronized (sw.getBuffer()) {
            try {
                return quote(string, sw).toString();
            } catch (IOException ignored) {
                // will never happen - we are writing to a string writer
                return "";
            }
        }
    }
static Writer org.json.JSONObject.quote (String string, Writer w) throws IOException [static]
Definition at line 1236 of file JSONObject.java.
References org.json.JSONObject.length().
                                                                           {
        if (string == null || string.length() == 0) {
            w.write("\"\"");
            return w;
        }
        char b;
        char c = 0;
        String hhhh;
        int i;
        int len = string.length();
        w.write('"');
        for (i = 0; i < len; i += 1) {
            b = c;
            c = string.charAt(i);
            switch (c) {
            case '\\':
            case '"':
                w.write('\\');
                w.write(c);
                break;
            case '/':
                if (b == '<') {
                    w.write('\\');
                }
                w.write(c);
                break;
            case '\b':
                w.write("\\b");
                break;
            case '\t':
                w.write("\\t");
                break;
            case '\n':
                w.write("\\n");
                break;
            case '\f':
                w.write("\\f");
                break;
            case '\r':
                w.write("\\r");
                break;
            default:
                if (c < ' ' || (c >= '\u0080' && c < '\u00a0')
                        || (c >= '\u2000' && c < '\u2100')) {
                    w.write("\\u");
                    hhhh = Integer.toHexString(c);
                    w.write("0000", 0, 4 - hhhh.length());
                    w.write(hhhh);
                } else {
                    w.write(c);
                }
            }
        }
        w.write('"');
        return w;
    }
Object org.json.JSONObject.remove (String key)
Remove a name and its value, if present.
Parameters
key The name to be removed.
Returns
The value that was associated with the name, or null if there was no value.
Definition at line 1303 of file JSONObject.java.
References org.json.JSONObject.map.
                                     {
        return this.map.remove(key);
    }
static Object org.json.JSONObject.stringToValue (String string) [static]
Try to convert a string into a number, boolean, or null. If the string can't be converted, return the string.
Parameters
string A String.
Returns
A simple JSON value.
Definition at line 1315 of file JSONObject.java.
References org.json.JSONObject.NULL.
Referenced by org.json.JSONTokener.nextValue().
                                                      {
        Double d;
        if (string.equals("")) {
            return string;
        }
        if (string.equalsIgnoreCase("true")) {
            return Boolean.TRUE;
        }
        if (string.equalsIgnoreCase("false")) {
            return Boolean.FALSE;
        }
        if (string.equalsIgnoreCase("null")) {
            return JSONObject.NULL;
        }
        /*
         * If it might be a number, try converting it. If a number cannot be
         * produced, then the value will just be a string.
         */
        char b = string.charAt(0);
        if ((b >= '0' && b <= '9') || b == '-') {
            try {
                if (string.indexOf('.') > -1 || string.indexOf('e') > -1
                        || string.indexOf('E') > -1) {
                    d = Double.valueOf(string);
                    if (!d.isInfinite() && !d.isNaN()) {
                        return d;
                    }
                } else {
                    Long myLong = new Long(string);
                    if (string.equals(myLong.toString())) {
                        if (myLong.longValue() == myLong.intValue()) {
                            return new Integer(myLong.intValue());
                        } else {
                            return myLong;
                        }
                    }
                }
            } catch (Exception ignore) {
            }
        }
        return string;
    }
static void org.json.JSONObject.testValidity (Object o) throws JSONException [static]
Throw an exception if the object is a NaN or infinite number.
Parameters
o The object to test.
Exceptions
JSONException If o is a non-finite number.
Definition at line 1368 of file JSONObject.java.
Referenced by org.json.JSONObject.accumulate(), org.json.JSONObject.append(), org.json.JSONObject.numberToString(), org.json.JSONArray.put(), and org.json.JSONObject.put().
                                                                   {
        if (o != null) {
            if (o instanceof Double) {
                if (((Double) o).isInfinite() || ((Double) o).isNaN()) {
                    throw new JSONException(
                            "JSON does not allow non-finite numbers.");
                }
            } else if (o instanceof Float) {
                if (((Float) o).isInfinite() || ((Float) o).isNaN()) {
                    throw new JSONException(
                            "JSON does not allow non-finite numbers.");
                }
            }
        }
    }
JSONArray org.json.JSONObject.toJSONArray (JSONArray names) throws JSONException
Produce a JSONArray containing the values of the members of this JSONObject.
Parameters
names A JSONArray containing a list of key strings. This determines the sequence of the values in the result.
Returns
A JSONArray of values.
Exceptions
JSONException If any of the values are non-finite numbers.
Definition at line 1395 of file JSONObject.java.
References org.json.JSONArray.getString(), org.json.JSONArray.length(), org.json.JSONObject.names(), org.json.JSONObject.opt(), and org.json.JSONArray.put().
Referenced by org.json.CDL.toString().
                                                                       {
        if (names == null || names.length() == 0) {
            return null;
        }
        JSONArray ja = new JSONArray();
        for (int i = 0; i < names.length(); i += 1) {
            ja.put(this.opt(names.getString(i)));
        }
        return ja;
    }
String org.json.JSONObject.toString ()
Make a JSON text of this JSONObject. For compactness, no whitespace is added. If this would not result in a syntactically correct JSON text, then null will be returned instead.
Warning: This method assumes that the data structure is acyclical.
Returns
a printable, displayable, portable, transmittable representation of the object, beginning with {
(left brace)
and ending with }
(right brace)
.
Definition at line 1418 of file JSONObject.java.
Referenced by org.json.CDL.toString().
                             {
        try {
            return this.toString(0);
        } catch (Exception e) {
            return null;
        }
    }
String org.json.JSONObject.toString (int indentFactor) throws JSONException
Make a prettyprinted JSON text of this JSONObject.
Warning: This method assumes that the data structure is acyclical.
Parameters
indentFactor The number of spaces to add to each level of indentation.
Returns
a printable, displayable, portable, transmittable representation of the object, beginning with {
(left brace)
and ending with }
(right brace)
.
Exceptions
JSONException If the object contains an invalid number.
Definition at line 1440 of file JSONObject.java.
References org.json.JSONObject.write().
                                                                  {
        StringWriter w = new StringWriter();
        synchronized (w.getBuffer()) {
            return this.write(w, indentFactor, 0).toString();
        }
    }
static String org.json.JSONObject.valueToString (Object value) throws JSONException [static]
Make a JSON text of an Object value. If the object has an value.toJSONString() method, then that method will be used to produce the JSON text. The method is required to produce a strictly conforming text. If the object does not contain a toJSONString method (which is the most common case), then a text will be produced by other means. If the value is an array or Collection, then a JSONArray will be made from it and its toJSONString method will be called. If the value is a MAP, then a JSONObject will be made from it and its toJSONString method will be called. Otherwise, the value's toString method will be called, and the result will be quoted.
Warning: This method assumes that the data structure is acyclical.
Parameters
value The value to be serialized.
Returns
a printable, displayable, transmittable representation of the object, beginning with {
(left brace)
and ending with }
(right brace)
.
Exceptions
JSONException If the value is or contains an invalid number.
Definition at line 1471 of file JSONObject.java.
References org.json.JSONObject.JSONObject(), org.json.JSONObject.numberToString(), and org.json.JSONObject.quote().
Referenced by org.json.JSONArray.join(), and org.json.JSONWriter.value().
                                                                          {
        if (value == null || value.equals(null)) {
            return "null";
        }
        if (value instanceof JSONString) {
            Object object;
            try {
                object = ((JSONString) value).toJSONString();
            } catch (Exception e) {
                throw new JSONException(e);
            }
            if (object instanceof String) {
                return (String) object;
            }
            throw new JSONException("Bad value from toJSONString: " + object);
        }
        if (value instanceof Number) {
            return numberToString((Number) value);
        }
        if (value instanceof Boolean || value instanceof JSONObject
                || value instanceof JSONArray) {
            return value.toString();
        }
        if (value instanceof Map) {
            return new JSONObject((Map) value).toString();
        }
        if (value instanceof Collection) {
            return new JSONArray((Collection) value).toString();
        }
        if (value.getClass().isArray()) {
            return new JSONArray(value).toString();
        }
        return quote(value.toString());
    }
static Object org.json.JSONObject.wrap (Object object) [static]
Wrap an object, if necessary. If the object is null, return the NULL object. If it is an array or collection, wrap it in a JSONArray. If it is a map, wrap it in a JSONObject. If it is a standard property (Double, String, et al) then it is already wrapped. Otherwise, if it comes from one of the java packages, turn it into a string. And if it doesn't, try to wrap it in a JSONObject. If the wrapping fails, then null is returned.
Parameters
object The object to wrap
Returns
The wrapped value
Definition at line 1518 of file JSONObject.java.
References org.json.JSONObject.JSONObject(), and org.json.JSONObject.NULL.
Referenced by org.json.JSONArray.JSONArray(), org.json.JSONObject.JSONObject(), and org.json.JSONObject.populateMap().
                                             {
        try {
            if (object == null) {
                return NULL;
            }
            if (object instanceof JSONObject || object instanceof JSONArray
                    || NULL.equals(object) || object instanceof JSONString
                    || object instanceof Byte || object instanceof Character
                    || object instanceof Short || object instanceof Integer
                    || object instanceof Long || object instanceof Boolean
                    || object instanceof Float || object instanceof Double
                    || object instanceof String) {
                return object;
            }
            if (object instanceof Collection) {
                return new JSONArray((Collection) object);
            }
            if (object.getClass().isArray()) {
                return new JSONArray(object);
            }
            if (object instanceof Map) {
                return new JSONObject((Map) object);
            }
            Package objectPackage = object.getClass().getPackage();
            String objectPackageName = objectPackage != null ? objectPackage
                    .getName() : "";
            if (objectPackageName.startsWith("java.")
                    || objectPackageName.startsWith("javax.")
                    || object.getClass().getClassLoader() == null) {
                return object.toString();
            }
            return new JSONObject(object);
        } catch (Exception exception) {
            return null;
        }
    }
Writer org.json.JSONObject.write (Writer writer) throws JSONException
Write the contents of the JSONObject as JSON text to a writer. For compactness, no whitespace is added.
Warning: This method assumes that the data structure is acyclical.
Returns
The writer.
Exceptions
JSONException
Definition at line 1565 of file JSONObject.java.
Referenced by org.json.JSONObject.toString().
                                                            {
        return this.write(writer, 0, 0);
    }
Writer org.json.JSONObject.write (Writer writer, int indentFactor, int indent) throws JSONException [package]
Write the contents of the JSONObject as JSON text to a writer. For compactness, no whitespace is added.
Warning: This method assumes that the data structure is acyclical.
Returns
The writer.
Exceptions
JSONException
Definition at line 1617 of file JSONObject.java.
References org.json.JSONObject.indent(), org.json.JSONObject.keys(), org.json.JSONObject.length(), org.json.JSONObject.map, org.json.JSONObject.quote(), and org.json.JSONObject.writeValue().
                                 {
        try {
            boolean commanate = false;
            final int length = this.length();
            Iterator keys = this.keys();
            writer.write('{');
            if (length == 1) {
                Object key = keys.next();
                writer.write(quote(key.toString()));
                writer.write(':');
                if (indentFactor > 0) {
                    writer.write(' ');
                }
                writeValue(writer, this.map.get(key), indentFactor,
      indent);
            } else if (length != 0) {
                final int newindent = indent + indentFactor;
                while (keys.hasNext()) {
                    Object key = keys.next();
                    if (commanate) {
                        writer.write(',');
                    }
                    if (indentFactor > 0) {
                        writer.write('\n');
                    }
                    indent(writer, newindent);
                    writer.write(quote(key.toString()));
                    writer.write(':');
                    if (indentFactor > 0) {
                        writer.write(' ');
                    }
                    writeValue(writer, this.map.get(key), indentFactor,
                            newindent);
                    commanate = true;
                }
                if (indentFactor > 0) {
                    writer.write('\n');
                }
                indent(writer, indent);
            }
            writer.write('}');
            return writer;
        } catch (IOException exception) {
            throw new JSONException(exception);
        }
    }
static final Writer org.json.JSONObject.writeValue (Writer writer, Object value, int indentFactor, int indent) throws JSONException, IOException [static], [package]
Definition at line 1569 of file JSONObject.java.
References org.json.JSONObject.indent(), org.json.JSONObject.JSONObject(), org.json.JSONObject.numberToString(), and org.json.JSONObject.quote().
Referenced by org.json.JSONArray.write(), and org.json.JSONObject.write().
                                                                            {
        if (value == null || value.equals(null)) {
            writer.write("null");
        } else if (value instanceof JSONObject) {
            ((JSONObject) value).write(writer, indentFactor, indent);
        } else if (value instanceof JSONArray) {
            ((JSONArray) value).write(writer, indentFactor, indent);
        } else if (value instanceof Map) {
            new JSONObject((Map) value).write(writer, indentFactor,
      indent);
        } else if (value instanceof Collection) {
            new JSONArray((Collection) value).write(writer, indentFactor,
                    indent);
        } else if (value.getClass().isArray()) {
            new JSONArray(value).write(writer, indentFactor, indent);
        } else if (value instanceof Number) {
            writer.write(numberToString((Number) value));
        } else if (value instanceof Boolean) {
            writer.write(value.toString());
        } else if (value instanceof JSONString) {
            Object o;
            try {
                o = ((JSONString) value).toJSONString();
            } catch (Exception e) {
                throw new JSONException(e);
            }
            writer.write(o != null ? o.toString() : quote(value.toString()));
        } else {
            quote(value.toString(), writer);
        }
        return writer;
    }
Member Data Documentation
HashMap org.json.JSONObject.keyPool = new HashMap(keyPoolSize) [static], [private]
Key pooling is like string interning, but without permanently tying up memory. To help conserve memory, storage of duplicated key strings in JSONObjects will be avoided by using a key pool to manage unique key string objects. This is used by JSONObject.put(string, object).
Definition at line 107 of file JSONObject.java.
Referenced by org.json.JSONObject.put().
final int org.json.JSONObject.keyPoolSize = 100 [static], [private]
The maximum number of keys in the key pool.
Definition at line 99 of file JSONObject.java.
Referenced by org.json.JSONObject.put().
final Map org.json.JSONObject.map [private]
The map where the JSONObject's properties are kept.
Definition at line 151 of file JSONObject.java.
Referenced by org.json.JSONObject.has(), org.json.JSONObject.JSONObject(), org.json.JSONObject.keySet(), org.json.JSONObject.length(), org.json.JSONObject.opt(), org.json.JSONObject.populateMap(), org.json.JSONObject.put(), org.json.JSONObject.remove(), and org.json.JSONObject.write().
final Object org.json.JSONObject.NULL = new Null() [static]
It is sometimes more convenient and less ambiguous to have a NULL object than to use Java's null value. JSONObject.NULL.equals(null) returns true. JSONObject.NULL.toString() returns `null`.
Definition at line 159 of file JSONObject.java.
Referenced by org.json.JSONArray.isNull(), org.json.JSONObject.isNull(), org.json.JSONArray.JSONArray(), org.json.JSONArray.optString(), org.json.JSONObject.optString(), org.json.JSONArray.put(), org.json.XML.stringToValue(), org.json.JSONObject.stringToValue(), and org.json.JSONObject.wrap().
The documentation for this class was generated from the following file:
org/json/JSONObject.java