org.json.XMLTokener Class Reference
Public Member Functions
XMLTokener (String s)
String nextCDATA () throws JSONException
Object nextContent () throws JSONException
Object nextEntity (char ampersand) throws JSONException
Object nextMeta () throws JSONException
Object nextToken () throws JSONException
boolean skipPast (String to) throws JSONException
Static Public Attributes
static final java.util.HashMap entity
Static Package Functions
[static initializer]
Additional Inherited Members
Detailed Description
The XMLTokener extends the JSONTokener to provide additional methods for the parsing of XML texts.
Author
JSON.org
Version
2012-11-13
Definition at line 33 of file XMLTokener.java.
Constructor & Destructor Documentation
org.json.XMLTokener.XMLTokener (String s)
Construct an XMLTokener from a string.
Parameters
s A source string.
Definition at line 54 of file XMLTokener.java.
                                {
        super(s);
    }
Member Function Documentation
org.json.XMLTokener.[static initializer] () [static], [package]
String org.json.XMLTokener.nextCDATA () throws JSONException
Get the text in the CDATA block.
Returns
The string up to the ]]>.
Exceptions
JSONException If the ]]> is not found.
Definition at line 63 of file XMLTokener.java.
References org.json.JSONTokener.end(), org.json.JSONTokener.next(), and org.json.JSONTokener.syntaxError().
                                                   {
        char c;
        int i;
        StringBuffer sb = new StringBuffer();
        for (;;) {
            c = next();
            if (end()) {
                throw syntaxError("Unclosed CDATA");
            }
            sb.append(c);
            i = sb.length() - 3;
            if (i >= 0 && sb.charAt(i) == ']' &&
                          sb.charAt(i + 1) == ']' && sb.charAt(i + 2) == '>') {
                sb.setLength(i);
                return sb.toString();
            }
        }
    }
Object org.json.XMLTokener.nextContent () throws JSONException
Get the next XML outer token, trimming whitespace. There are two kinds of tokens: the '<' character which begins a markup tag, and the content text between markup tags.
Returns
A string, or a '<' Character, or null if there is no more source text.
Exceptions
JSONException
Definition at line 92 of file XMLTokener.java.
References org.json.JSONTokener.back(), org.json.XML.LT, org.json.JSONTokener.next(), and org.json.XMLTokener.nextEntity().
                                                     {
        char c;
        StringBuffer sb;
        do {
            c = next();
        } while (Character.isWhitespace(c));
        if (c == 0) {
            return null;
        }
        if (c == '<') {
            return XML.LT;
        }
        sb = new StringBuffer();
        for (;;) {
            if (c == '<' || c == 0) {
                back();
                return sb.toString().trim();
            }
            if (c == '&') {
                sb.append(nextEntity(c));
            } else {
                sb.append(c);
            }
            c = next();
        }
    }
Object org.json.XMLTokener.nextEntity (char ampersand) throws JSONException
Return the next entity. These entities are translated to Characters: & ' > < ".
Parameters
ampersand An ampersand character.
Returns
A Character or an entity String if the entity is not recognized.
Exceptions
JSONException If missing ';' in XML entity.
Definition at line 127 of file XMLTokener.java.
References org.json.XMLTokener.entity, org.json.JSONTokener.next(), and org.json.JSONTokener.syntaxError().
Referenced by org.json.XMLTokener.nextContent(), and org.json.XMLTokener.nextToken().
                                                                  {
        StringBuffer sb = new StringBuffer();
        for (;;) {
            char c = next();
            if (Character.isLetterOrDigit(c) || c == '#') {
                sb.append(Character.toLowerCase(c));
            } else if (c == ';') {
                break;
            } else {
                throw syntaxError("Missing ';' in XML entity: &" + sb);
            }
        }
        String string = sb.toString();
        Object object = entity.get(string);
        return object != null ? object : ampersand + string + ";";
    }
Object org.json.XMLTokener.nextMeta () throws JSONException
Returns the next XML meta token. This is used for skipping over <!...> and <?...?> structures.
Returns
Syntax characters (< > / = ! ?) are returned as Character, and strings and names are returned as Boolean. We don't care what the values actually are.
Exceptions
JSONException If a string is not properly closed or if the XML is badly structured.
Definition at line 154 of file XMLTokener.java.
References org.json.JSONTokener.back(), org.json.XML.BANG, org.json.XML.EQ, org.json.XML.GT, org.json.XML.LT, org.json.JSONTokener.next(), org.json.XML.QUEST, org.json.XML.SLASH, and org.json.JSONTokener.syntaxError().
                                                  {
        char c;
        char q;
        do {
            c = next();
        } while (Character.isWhitespace(c));
        switch (c) {
        case 0:
            throw syntaxError("Misshaped meta tag");
        case '<':
            return XML.LT;
        case '>':
            return XML.GT;
        case '/':
            return XML.SLASH;
        case '=':
            return XML.EQ;
        case '!':
            return XML.BANG;
        case '?':
            return XML.QUEST;
        case '"':
        case '\'':
            q = c;
            for (;;) {
                c = next();
                if (c == 0) {
                    throw syntaxError("Unterminated string");
                }
                if (c == q) {
                    return Boolean.TRUE;
                }
            }
        default:
            for (;;) {
                c = next();
                if (Character.isWhitespace(c)) {
                    return Boolean.TRUE;
                }
                switch (c) {
                case 0:
                case '<':
                case '>':
                case '/':
                case '=':
                case '!':
                case '?':
                case '"':
                case '\'':
                    back();
                    return Boolean.TRUE;
                }
            }
        }
    }
Object org.json.XMLTokener.nextToken () throws JSONException
Get the next XML Token. These tokens are found inside of angle brackets. It may be one of these characters: / > = ! ? or it may be a string wrapped in single quotes or double quotes, or it may be a name.
Returns
a String or a Character.
Exceptions
JSONException If the XML is not well formed.
Definition at line 219 of file XMLTokener.java.
References org.json.JSONTokener.back(), org.json.XML.BANG, org.json.XML.EQ, org.json.XML.GT, org.json.JSONTokener.next(), org.json.XMLTokener.nextEntity(), org.json.XML.QUEST, org.json.XML.SLASH, and org.json.JSONTokener.syntaxError().
                                                   {
        char c;
        char q;
        StringBuffer sb;
        do {
            c = next();
        } while (Character.isWhitespace(c));
        switch (c) {
        case 0:
            throw syntaxError("Misshaped element");
        case '<':
            throw syntaxError("Misplaced '<'");
        case '>':
            return XML.GT;
        case '/':
            return XML.SLASH;
        case '=':
            return XML.EQ;
        case '!':
            return XML.BANG;
        case '?':
            return XML.QUEST;
// Quoted string
        case '"':
        case '\'':
            q = c;
            sb = new StringBuffer();
            for (;;) {
                c = next();
                if (c == 0) {
                    throw syntaxError("Unterminated string");
                }
                if (c == q) {
                    return sb.toString();
                }
                if (c == '&') {
                    sb.append(nextEntity(c));
                } else {
                    sb.append(c);
                }
            }
        default:
// Name
            sb = new StringBuffer();
            for (;;) {
                sb.append(c);
                c = next();
                if (Character.isWhitespace(c)) {
                    return sb.toString();
                }
                switch (c) {
                case 0:
                    return sb.toString();
                case '>':
                case '/':
                case '=':
                case '!':
                case '?':
                case '[':
                case ']':
                    back();
                    return sb.toString();
                case '<':
                case '"':
                case '\'':
                    throw syntaxError("Bad character in a name");
                }
            }
        }
    }
boolean org.json.XMLTokener.skipPast (String to) throws JSONException
Skip characters until past the requested string. If it is not found, we are left at the end of the source with a result of false.
Parameters
to A string to skip past.
Exceptions
JSONException
Definition at line 301 of file XMLTokener.java.
References org.json.JSONTokener.next().
Referenced by org.json.XML.toJSONObject().
                                                            {
        boolean b;
        char c;
        int i;
        int j;
        int offset = 0;
        int length = to.length();
        char[] circle = new char[length];
        /*
         * First fill the circle buffer with as many characters as are in the
         * to string. If we reach an early end, bail.
         */
        for (i = 0; i < length; i += 1) {
            c = next();
            if (c == 0) {
                return false;
            }
            circle[i] = c;
        }
        /* We will loop, possibly for all of the remaining characters. */
        for (;;) {
            j = offset;
            b = true;
            /* Compare the circle buffer with the to string. */
            for (i = 0; i < length; i += 1) {
                if (circle[j] != to.charAt(i)) {
                    b = false;
                    break;
                }
                j += 1;
                if (j >= length) {
                    j -= length;
                }
            }
            /* If we exit the loop with b intact, then victory is ours. */
            if (b) {
                return true;
            }
            /* Get the next character. If there isn't one, then defeat is ours. */
            c = next();
            if (c == 0) {
                return false;
            }
            /*
             * Shove the character in the circle buffer and advance the
             * circle offset. The offset is mod n.
             */
            circle[offset] = c;
            offset += 1;
            if (offset >= length) {
                offset -= length;
            }
        }
    }
Member Data Documentation
final java.util.HashMap org.json.XMLTokener.entity [static]
The table of entity values. It initially contains Character values for amp, apos, gt, lt, quot.
Definition at line 39 of file XMLTokener.java.
Referenced by org.json.XMLTokener.nextEntity().
The documentation for this class was generated from the following file:
org/json/XMLTokener.java