org.json.HTTP Class Reference
Static Public Member Functions
static JSONObject toJSONObject (String string) throws JSONException
static String toString (JSONObject jo) throws JSONException
Static Public Attributes
static final String CRLF = `\r\n`
Detailed Description
Convert an HTTP header to a JSONObject and back.
Author
JSON.org
Version
2010-12-24
Definition at line 34 of file HTTP.java.
Member Function Documentation
static JSONObject org.json.HTTP.toJSONObject (String string) throws JSONException [static]
Convert an HTTP header string into a JSONObject. It can be a request header or a response header. A request header will contain
{
   Method: "POST" (for example),
   "Request-URI": "/" (for example),
   "HTTP-Version": "HTTP/1.1" (for example)
}
 A response header will contain
{
   "HTTP-Version": "HTTP/1.1" (for example),
   "Status-Code": "200" (for example),
   "Reason-Phrase": "OK" (for example)
}
 In addition, the other parameters in the header will be captured, using the HTTP field names as JSON names, so that
   Date: Sun, 26 May 2002 18:06:04 GMT
   Cookie: Q=q2=PPEAsg--; B=677gi6ouf29bn&b=2&f=s
   Cache-Control: no-cache
 become
{...
   Date: "Sun, 26 May 2002 18:06:04 GMT",
   Cookie: "Q=q2=PPEAsg--; B=677gi6ouf29bn b=2 f=s",
   "Cache-Control": "no-cache",
...}
 It does no further checking or conversion. It does not parse dates. It does not do '' transforms on URLs.
Parameters
string An HTTP header string.
Returns
A JSONObject containing the elements and attributes of the XML string.
Exceptions
JSONException
Definition at line 71 of file HTTP.java.
References org.json.JSONTokener.more(), org.json.JSONTokener.next(), org.json.JSONTokener.nextTo(), org.json.HTTPTokener.nextToken(), and org.json.JSONObject.put().
                                                                              {
        JSONObject jo = new JSONObject();
        HTTPTokener x = new HTTPTokener(string);
        String token;
        token = x.nextToken();
        if (token.toUpperCase().startsWith("HTTP")) {
// Response
            jo.put("HTTP-Version", token);
            jo.put("Status-Code", x.nextToken());
            jo.put("Reason-Phrase", x.nextTo('\0'));
            x.next();
        } else {
// Request
            jo.put("Method", token);
            jo.put("Request-URI", x.nextToken());
            jo.put("HTTP-Version", x.nextToken());
        }
// Fields
        while (x.more()) {
            String name = x.nextTo(':');
            x.next(':');
            jo.put(name, x.nextTo('\0'));
            x.next();
        }
        return jo;
    }
static String org.json.HTTP.toString (JSONObject jo) throws JSONException [static]
Convert a JSONObject into an HTTP header. A request header must contain
{
   Method: "POST" (for example),
   "Request-URI": "/" (for example),
   "HTTP-Version": "HTTP/1.1" (for example)
}
 A response header must contain
{
   "HTTP-Version": "HTTP/1.1" (for example),
   "Status-Code": "200" (for example),
   "Reason-Phrase": "OK" (for example)
}
 Any other members of the JSONObject will be output as HTTP fields. The result will end with two CRLF pairs.
Parameters
jo A JSONObject
Returns
An HTTP header string.
Exceptions
JSONException if the object does not contain enough information.
Definition at line 127 of file HTTP.java.
References org.json.HTTP.CRLF.
                                                                      {
        Iterator keys = jo.keys();
        String string;
        StringBuffer sb = new StringBuffer();
        if (jo.has("Status-Code") && jo.has("Reason-Phrase")) {
            sb.append(jo.getString("HTTP-Version"));
            sb.append(' ');
            sb.append(jo.getString("Status-Code"));
            sb.append(' ');
            sb.append(jo.getString("Reason-Phrase"));
        } else if (jo.has("Method") && jo.has("Request-URI")) {
            sb.append(jo.getString("Method"));
            sb.append(' ');
            sb.append('"');
            sb.append(jo.getString("Request-URI"));
            sb.append('"');
            sb.append(' ');
            sb.append(jo.getString("HTTP-Version"));
        } else {
            throw new JSONException("Not enough material for an HTTP header.");
        }
        sb.append(CRLF);
        while (keys.hasNext()) {
            string = keys.next().toString();
            if (!"HTTP-Version".equals(string) && !"Status-Code".equals(string) &&
                    !"Reason-Phrase".equals(string) && !"Method".equals(string) &&
                    !"Request-URI".equals(string) && !jo.isNull(string)) {
                sb.append(string);
                sb.append(": ");
                sb.append(jo.getString(string));
                sb.append(CRLF);
            }
        }
        sb.append(CRLF);
        return sb.toString();
    }
Member Data Documentation
final String org.json.HTTP.CRLF = `\r\n` [static]
Carriage return/line feed.
Definition at line 37 of file HTTP.java.
Referenced by org.json.HTTP.toString().
The documentation for this class was generated from the following file:
org/json/HTTP.java