org.facebook.crawler.FacebookJsonParser Class Reference
Public Member Functions
FacebookJsonParser (FacebookDatabase db, String accessToken, String[] Fields, String[] GroupIDs)
void crawlJson (CrawlOptions op) throws IOException, JSONException, SQLException
Private Member Functions
void crawlGroup () throws IOException, JSONException, SQLException
void crawlUsers () throws IOException, JSONException, SQLException
void crawlUser (JSONObject GroupMemberJSONObject, int IDIndex) throws IOException, JSONException, SQLException
Static Private Member Functions
static String readAll (Reader rd) throws IOException
static String trim (String stringToTrim)
static JSONObject readJsonFromUrl (String url) throws IOException, JSONException
Private Attributes
String accessToken
String GraphURL = `https://graph.facebook.com/`
String GroupID [] = {}
String UserID [] = {}
String Fields [] = {}
FacebookDatabase db
Detailed Description
Definition at line 30 of file FacebookJsonParser.java.
Constructor & Destructor Documentation
org.facebook.crawler.FacebookJsonParser.FacebookJsonParser (FacebookDatabase db, String accessToken, String[] Fields, String[] GroupIDs)
Definition at line 44 of file FacebookJsonParser.java.
References org.facebook.crawler.FacebookJsonParser.accessToken, org.facebook.crawler.FacebookJsonParser.db, org.facebook.crawler.FacebookJsonParser.Fields, and org.facebook.crawler.FacebookJsonParser.GroupID.
                                                                                                           
         {
        this.db = db;
        this.accessToken = accessToken;
        this.Fields = Fields;
        this.GroupID = GroupIDs;
    }
Member Function Documentation
void org.facebook.crawler.FacebookJsonParser.crawlGroup () throws IOException, JSONException, SQLException [private]
Definition at line 86 of file FacebookJsonParser.java.
References org.facebook.crawler.FacebookJsonParser.accessToken, org.facebook.crawler.FacebookJsonParser.crawlUser(), org.json.JSONObject.getJSONArray(), org.json.JSONArray.getJSONObject(), org.facebook.crawler.FacebookJsonParser.GraphURL, org.facebook.crawler.FacebookJsonParser.GroupID, org.json.JSONArray.length(), and org.facebook.crawler.FacebookJsonParser.readJsonFromUrl().
Referenced by org.facebook.crawler.FacebookJsonParser.crawlJson().
                                                                              { // Crawl entire group info,
       including it's members.
        
        
        String memberListAppend = "/members?access_token=" + this.accessToken;
                
        for(int GroupIDIndex = 0 ; GroupIDIndex < GroupID.length ; GroupIDIndex++) {
            
            String GroupURL = this.GraphURL;
            GroupURL = GroupURL.concat(GroupID[GroupIDIndex]);
            GroupURL = GroupURL.concat(memberListAppend); //Group members list & id
            System.out.println(GroupURL);
      
            JSONObject GroupJSONObject = readJsonFromUrl(GroupURL);
            JSONArray GroupMemberListJSONArray = GroupJSONObject.getJSONArray("data");
            
            for(int MemberCount = 0; MemberCount < GroupMemberListJSONArray.length(); MemberCount++) {
                this.crawlUser(GroupMemberListJSONArray.getJSONObject(MemberCount) ,
      GroupIDIndex);
                
            }
            
            
        }
        
    }
void org.facebook.crawler.FacebookJsonParser.crawlJson (CrawlOptions op) throws IOException, JSONException, SQLException
Definition at line 246 of file FacebookJsonParser.java.
References org.facebook.crawler.FacebookJsonParser.crawlGroup(), org.facebook.crawler.FacebookJsonParser.crawlUsers(), org.facebook.crawler.FacebookDatabase.createStatement(), org.facebook.crawler.FacebookJsonParser.db, org.facebook.crawler.FacebookDatabase.destroyDatabaseConnection(), org.facebook.crawler.FacebookJsonParser.GroupID, and org.facebook.crawler.FacebookDatabase.initDatabaseConnection().
Referenced by org.facebook.crawler.CrawlerClient.main().
                                                                                             {
        
        this.db.initDatabaseConnection();
        this.db.createStatement();
        
        //If Group Crawl
        if(op.toString().equals("GROUP") && GroupID.length > 0)
            this.crawlGroup();
        
        //If Users Crawl
        else if(op.toString().equalsIgnoreCase("USER")){
            this.crawlUsers();
        }
        
        else {
            System.err.println("Parameters missing.");
        }
        this.db.destroyDatabaseConnection();
         
        
    }
void org.facebook.crawler.FacebookJsonParser.crawlUser (JSONObject GroupMemberJSONObject, int IDIndex) throws IOException, JSONException, SQLException [private]
Definition at line 130 of file FacebookJsonParser.java.
References org.facebook.crawler.FacebookJsonParser.accessToken, org.facebook.crawler.FacebookJsonParser.db, org.facebook.crawler.FacebookDatabase.executeQuery(), org.facebook.crawler.FacebookJsonParser.Fields, org.json.JSONObject.getJSONArray(), org.json.JSONArray.getJSONObject(), org.json.JSONObject.getJSONObject(), org.json.JSONObject.getNames(), org.json.JSONArray.getString(), org.json.JSONObject.getString(), org.facebook.crawler.FacebookJsonParser.GraphURL, org.facebook.crawler.FacebookJsonParser.GroupID, org.json.JSONArray.length(), org.json.JSONObject.names(), org.facebook.crawler.FacebookJsonParser.readJsonFromUrl(), and org.facebook.crawler.FacebookJsonParser.trim().
Referenced by org.facebook.crawler.FacebookJsonParser.crawlGroup(), and org.facebook.crawler.FacebookJsonParser.crawlUsers().
                                                                                                           
                        { // Crawl individual user info. Pass list of userIDs to crawl.
        
        String accessTokenAppend = "?access_token=" + accessToken;
        String MemberURL;
        String ID = "";
        JSONObject GroupMemberDataJSONObject;
        
        MemberURL = GraphURL;
        MemberURL = MemberURL.concat(GroupMemberJSONObject.getString("id"));
        MemberURL = MemberURL.concat(accessTokenAppend);
        
        GroupMemberDataJSONObject = readJsonFromUrl(MemberURL); // Member info
        //System.out.println(GroupMemberDataJSONObject.get("name"));
        String MemberDataFieldsArray[] = new String[19];
        String currentField = "";
        JSONArray MemberDataFieldNames = GroupMemberDataJSONObject.names();
            for(int fieldIndex = 0; fieldIndex < MemberDataFieldNames.length(); fieldIndex++) {
                String check = MemberDataFieldNames.getString(fieldIndex);
                //TODO Need to clean & compact this code section. Crawler will expand support for every
       field in the User object, but
                // database schema must be updated first to include all the fields.
                if(check.equals("id") || check.equals("name") || check.equals("first_name") || check.
      equals("middle_name") || check.equals("last_name") || check.equals("link") ||check.equals("username") ||check.
      equals("birthday") ||check.equals("gender") ||check.equals("relationship_status") ||check.equals("bio") ||check
      .equals("quotes") ||check.equals("email") ||check.equals("religion")) {
                    
                          currentField = GroupMemberDataJSONObject.getString(MemberDataFieldNames.
      getString(fieldIndex));
                }
                if(MemberDataFieldNames.getString(fieldIndex).equals("location")) {
                    String locarr[] = JSONObject.getNames(GroupMemberDataJSONObject.getJSONObject("location
      "));
                    for(int z=0; z<locarr.length; z++)
                        if(locarr[z].equals("name"))
                            currentField = GroupMemberDataJSONObject.getString(locarr[z]);
    
                }
                if(MemberDataFieldNames.getString(fieldIndex).equals("hometown")) {
                    String homearr[] = JSONObject.getNames(GroupMemberDataJSONObject.getJSONObject("
      hometown"));
                    for(int z = 0; z < homearr.length; z++)
                        if(homearr[z].equals("name"))
                            currentField = GroupMemberDataJSONObject.getString(homearr[z]);
                }
                if(MemberDataFieldNames.getString(fieldIndex).equals("languages")) {
                    String langs = "";
                    JSONArray langarry = GroupMemberDataJSONObject.getJSONArray("languages");
                    JSONObject langnames;
                    for(int y=0; y<langarry.length(); y++){
                        langnames = langarry.getJSONObject(y);
                        langs = langs.concat(" " + langnames.getString("name") + " ");
                    }
                    currentField = langs;
                }
                if(MemberDataFieldNames.getString(fieldIndex).equals("education")) {
                    String education = "";
                    JSONArray eduarry = GroupMemberDataJSONObject.getJSONArray("education");
                    JSONObject eduname;
                    String scharry[] = JSONObject.getNames(GroupMemberDataJSONObject.getJSONObject("
      education"));
                    for(int x = 0; x < eduarry.length(); x++){
                        if(scharry[x].equals("school"))
                        {
                            eduname = eduarry.getJSONObject(x);
                            education = education.concat(" " + eduname.getString("name") + " ");
                        }
    
                    }
                    currentField = education;
                }
                
                if(MemberDataFieldNames.getString(fieldIndex).equals("work")) {
                    String work = "";
                    JSONArray workarry = GroupMemberDataJSONObject.getJSONArray("work");
                    JSONObject workname;
                    String wrkarry[] = JSONObject.getNames(GroupMemberDataJSONObject.getJSONObject("work")
       );
                    for(int w=0; w<workarry.length(); w++){
                        if(wrkarry[w].equals("employer"))
                        {
                            workname = workarry.getJSONObject(w);
                            work = work.concat(" " + workname.getString("name") + " ");
                        }
    
                    }
                    currentField = work;
                }
                String tempcheck = MemberDataFieldNames.getString(fieldIndex);
                
                for(int x = 0; x < Fields.length; x++){
                    if(tempcheck.equals(Fields[x])){
                        
                        currentField = trim(currentField);
                        if(currentField != null)
                        MemberDataFieldsArray[x] = currentField;
                        
                        else
                            MemberDataFieldsArray[x] = "null";
                        
                    }
                }
                ID = GroupMemberDataJSONObject.getString("id");
                
            }
        //for(int j=0; j<MemberDataFieldsArray.length; j++){
       System.out.println(MemberDataFieldsArray[j]);}
        this.db.executeQuery(ID , MemberDataFieldsArray , GroupID , IDIndex);
        
        
    }
void org.facebook.crawler.FacebookJsonParser.crawlUsers () throws IOException, JSONException, SQLException [private]
Definition at line 111 of file FacebookJsonParser.java.
References org.facebook.crawler.FacebookJsonParser.accessToken, org.facebook.crawler.FacebookJsonParser.crawlUser(), org.facebook.crawler.FacebookJsonParser.GraphURL, org.json.JSONObject.put(), and org.facebook.crawler.FacebookJsonParser.UserID.
Referenced by org.facebook.crawler.FacebookJsonParser.crawlJson().
                                                                              {
    
        String accessTokenAppend = "?access_token=" + accessToken;
                
        if(UserID.length > 0)
        for(int UserIDIndex = 0; UserIDIndex < UserID.length; UserIDIndex++){
            
            String UserURL = this.GraphURL;
            UserURL = UserURL.concat(UserID[ UserIDIndex ]);
            UserURL = UserURL.concat(accessTokenAppend);
            
            JSONObject UserObject = new JSONObject();
            UserObject.put("id" , UserID[UserIDIndex]);
            this.crawlUser(UserObject , -1);
            
        }
            
    }
static String org.facebook.crawler.FacebookJsonParser.readAll (Reader rd) throws IOException [static], [private]
Definition at line 51 of file FacebookJsonParser.java.
Referenced by org.facebook.crawler.FacebookJsonParser.readJsonFromUrl().
                                                                {
        StringBuilder sb = new StringBuilder();
        int cp;
    
        while ((cp = rd.read()) != -1) {
            sb.append((char) cp);
        }
    
        return sb.toString();
    }
static JSONObject org.facebook.crawler.FacebookJsonParser.readJsonFromUrl (String url) throws IOException, JSONException [static], [private]
Definition at line 70 of file FacebookJsonParser.java.
References org.facebook.crawler.FacebookJsonParser.readAll().
Referenced by org.facebook.crawler.FacebookJsonParser.crawlGroup(), and org.facebook.crawler.FacebookJsonParser.crawlUser().
                                                                                            {
    
        InputStream is = new URL(url).openStream();
   
        try {
        
            BufferedReader rd = new BufferedReader(new InputStreamReader(is, Charset.forName("UTF-8")));
            String jsonText = readAll(rd);
            JSONObject json = new JSONObject(jsonText);
            return json;
        
        } finally {
            is.close();
        }
    }
static String org.facebook.crawler.FacebookJsonParser.trim (String stringToTrim) [static], [private]
Definition at line 63 of file FacebookJsonParser.java.
Referenced by org.facebook.crawler.FacebookJsonParser.crawlUser().
                                                      {
        
        return stringToTrim.replace('\'', ' ');
    
    }
Member Data Documentation
String org.facebook.crawler.FacebookJsonParser.accessToken [private]
Definition at line 32 of file FacebookJsonParser.java.
Referenced by org.facebook.crawler.FacebookJsonParser.crawlGroup(), org.facebook.crawler.FacebookJsonParser.crawlUser(), org.facebook.crawler.FacebookJsonParser.crawlUsers(), and org.facebook.crawler.FacebookJsonParser.FacebookJsonParser().
FacebookDatabase org.facebook.crawler.FacebookJsonParser.db [private]
Definition at line 41 of file FacebookJsonParser.java.
Referenced by org.facebook.crawler.FacebookJsonParser.crawlJson(), org.facebook.crawler.FacebookJsonParser.crawlUser(), and org.facebook.crawler.FacebookJsonParser.FacebookJsonParser().
String org.facebook.crawler.FacebookJsonParser.Fields[] = {} [private]
Definition at line 37 of file FacebookJsonParser.java.
Referenced by org.facebook.crawler.FacebookJsonParser.crawlUser(), and org.facebook.crawler.FacebookJsonParser.FacebookJsonParser().
String org.facebook.crawler.FacebookJsonParser.GraphURL = `https://graph.facebook.com/` [private]
Definition at line 33 of file FacebookJsonParser.java.
Referenced by org.facebook.crawler.FacebookJsonParser.crawlGroup(), org.facebook.crawler.FacebookJsonParser.crawlUser(), and org.facebook.crawler.FacebookJsonParser.crawlUsers().
String org.facebook.crawler.FacebookJsonParser.GroupID[] = {} [private]
Definition at line 35 of file FacebookJsonParser.java.
Referenced by org.facebook.crawler.FacebookJsonParser.crawlGroup(), org.facebook.crawler.FacebookJsonParser.crawlJson(), org.facebook.crawler.FacebookJsonParser.crawlUser(), and org.facebook.crawler.FacebookJsonParser.FacebookJsonParser().
String org.facebook.crawler.FacebookJsonParser.UserID[] = {} [private]
Definition at line 36 of file FacebookJsonParser.java.
Referenced by org.facebook.crawler.FacebookJsonParser.crawlUsers().
The documentation for this class was generated from the following file:
org/facebook/crawler/FacebookJsonParser.java