org.json.CDL Class Reference
Static Public Member Functions
static JSONArray rowToJSONArray (JSONTokener x) throws JSONException
static JSONObject rowToJSONObject (JSONArray names, JSONTokener x) throws JSONException
static String rowToString (JSONArray ja)
static JSONArray toJSONArray (String string) throws JSONException
static JSONArray toJSONArray (JSONTokener x) throws JSONException
static JSONArray toJSONArray (JSONArray names, String string) throws JSONException
static JSONArray toJSONArray (JSONArray names, JSONTokener x) throws JSONException
static String toString (JSONArray ja) throws JSONException
static String toString (JSONArray names, JSONArray ja) throws JSONException
Static Private Member Functions
static String getValue (JSONTokener x) throws JSONException
Detailed Description
This provides static methods to convert comma delimited text into a JSONArray, and to covert a JSONArray into comma delimited text. Comma delimited text is a very popular format for data interchange. It is understood by most database, spreadsheet, and organizer programs.
Each row of text represents a row in a table or a data record. Each row ends with a NEWLINE character. Each row contains one or more values. Values are separated by commas. A value can contain any character except for comma, unless is is wrapped in single quotes or double quotes.
The first row usually contains the names of the columns.
A comma delimited list can be converted into a JSONArray of JSONObjects. The names for the elements in the JSONObjects can be taken from the names in the first row.
Author
JSON.org
Version
2012-11-13
Definition at line 46 of file CDL.java.
Member Function Documentation
static String org.json.CDL.getValue (JSONTokener x) throws JSONException [static], [private]
Get the next value. The value can be wrapped in quotes. The value can be empty.
Parameters
x A JSONTokener of the source text.
Returns
The value string, or null if empty.
Exceptions
JSONException if the quoted string is badly formed.
Definition at line 55 of file CDL.java.
Referenced by org.json.CDL.rowToJSONArray().
                                                                       {
        char c;
        char q;
        StringBuffer sb;
        do {
            c = x.next();
        } while (c == ' ' || c == '\t');
        switch (c) {
        case 0:
            return null;
        case '"':
        case '\'':
            q = c;
            sb = new StringBuffer();
            for (;;) {
                c = x.next();
                if (c == q) {
                    break;
                }
                if (c == 0 || c == '\n' || c == '\r') {
                    throw x.syntaxError("Missing close quote '" + q + "'.");
                }
                sb.append(c);
            }
            return sb.toString();
        case ',':
            x.back();
            return "";
        default:
            x.back();
            return x.nextTo(',');
        }
    }
static JSONArray org.json.CDL.rowToJSONArray (JSONTokener x) throws JSONException [static]
Produce a JSONArray of strings from a row of comma delimited values.
Parameters
x A JSONTokener of the source text.
Returns
A JSONArray of strings.
Exceptions
JSONException
Definition at line 95 of file CDL.java.
References org.json.CDL.getValue(), org.json.JSONArray.length(), and org.json.JSONArray.put().
Referenced by org.json.CDL.rowToJSONObject(), and org.json.CDL.toJSONArray().
                                                                               {
        JSONArray ja = new JSONArray();
        for (;;) {
            String value = getValue(x);
            char c = x.next();
            if (value == null ||
                    (ja.length() == 0 && value.length() == 0 && c != ',')) {
                return null;
            }
            ja.put(value);
            for (;;) {
                if (c == ',') {
                    break;
                }
                if (c != ' ') {
                    if (c == '\n' || c == '\r' || c == 0) {
                        return ja;
                    }
                    throw x.syntaxError("Bad character '" + c + "' (" +
                            (int)c + ").");
                }
                c = x.next();
            }
        }
    }
static JSONObject org.json.CDL.rowToJSONObject (JSONArray names, JSONTokener x) throws JSONException [static]
Produce a JSONObject from a row of comma delimited text, using a parallel JSONArray of strings to provides the names of the elements.
Parameters
names A JSONArray of names. This is commonly obtained from the first row of a comma delimited text file using the rowToJSONArray method.
x A JSONTokener of the source text.
Returns
A JSONObject combining the names and values.
Exceptions
JSONException
Definition at line 131 of file CDL.java.
References org.json.CDL.rowToJSONArray(), and org.json.JSONArray.toJSONObject().
Referenced by org.json.CDL.toJSONArray().
                                 {
        JSONArray ja = rowToJSONArray(x);
        return ja != null ? ja.toJSONObject(names) : null;
    }
static String org.json.CDL.rowToString (JSONArray ja) [static]
Produce a comma delimited text row from a JSONArray. Values containing the comma character will be quoted. Troublesome characters may be removed.
Parameters
ja A JSONArray of strings.
Returns
A string ending in NEWLINE.
Definition at line 144 of file CDL.java.
References org.json.JSONArray.length(), and org.json.JSONArray.opt().
Referenced by org.json.CDL.toString().
                                                   {
        StringBuffer sb = new StringBuffer();
        for (int i = 0; i < ja.length(); i += 1) {
            if (i > 0) {
                sb.append(',');
            }
            Object object = ja.opt(i);
            if (object != null) {
                String string = object.toString();
                if (string.length() > 0 && (string.indexOf(',') >= 0 ||
                        string.indexOf('\n') >= 0 || string.indexOf('\r') >= 0 ||
                        string.indexOf(0) >= 0 || string.charAt(0) == '"')) {
                    sb.append('"');
                    int length = string.length();
                    for (int j = 0; j < length; j += 1) {
                        char c = string.charAt(j);
                        if (c >= ' ' && c != '"') {
                            sb.append(c);
                        }
                    }
                    sb.append('"');
                } else {
                    sb.append(string);
                }
            }
        }
        sb.append('\n');
        return sb.toString();
    }
static JSONArray org.json.CDL.toJSONArray (String string) throws JSONException [static]
Produce a JSONArray of JSONObjects from a comma delimited text string, using the first row as a source of names.
Parameters
string The comma delimited text.
Returns
A JSONArray of JSONObjects.
Exceptions
JSONException
Definition at line 181 of file CDL.java.
Referenced by org.json.CDL.toJSONArray().
                                                                            {
        return toJSONArray(new JSONTokener(string));
    }
static JSONArray org.json.CDL.toJSONArray (JSONTokener x) throws JSONException [static]
Produce a JSONArray of JSONObjects from a comma delimited text string, using the first row as a source of names.
Parameters
x The JSONTokener containing the comma delimited text.
Returns
A JSONArray of JSONObjects.
Exceptions
JSONException
Definition at line 192 of file CDL.java.
References org.json.CDL.rowToJSONArray(), and org.json.CDL.toJSONArray().
                                                                            {
        return toJSONArray(rowToJSONArray(x), x);
    }
static JSONArray org.json.CDL.toJSONArray (JSONArray names, String string) throws JSONException [static]
Produce a JSONArray of JSONObjects from a comma delimited text string using a supplied JSONArray as the source of element names.
Parameters
names A JSONArray of strings.
string The comma delimited text.
Returns
A JSONArray of JSONObjects.
Exceptions
JSONException
Definition at line 204 of file CDL.java.
References org.json.CDL.toJSONArray().
                                 {
        return toJSONArray(names, new JSONTokener(string));
    }
static JSONArray org.json.CDL.toJSONArray (JSONArray names, JSONTokener x) throws JSONException [static]
Produce a JSONArray of JSONObjects from a comma delimited text string using a supplied JSONArray as the source of element names.
Parameters
names A JSONArray of strings.
x A JSONTokener of the source text.
Returns
A JSONArray of JSONObjects.
Exceptions
JSONException
Definition at line 217 of file CDL.java.
References org.json.JSONArray.length(), org.json.JSONArray.put(), and org.json.CDL.rowToJSONObject().
                                 {
        if (names == null || names.length() == 0) {
            return null;
        }
        JSONArray ja = new JSONArray();
        for (;;) {
            JSONObject jo = rowToJSONObject(names, x);
            if (jo == null) {
                break;
            }
            ja.put(jo);
        }
        if (ja.length() == 0) {
            return null;
        }
        return ja;
    }
static String org.json.CDL.toString (JSONArray ja) throws JSONException [static]
Produce a comma delimited text from a JSONArray of JSONObjects. The first row will be a list of names obtained by inspecting the first JSONObject.
Parameters
ja A JSONArray of JSONObjects.
Returns
A comma delimited text.
Exceptions
JSONException
Definition at line 245 of file CDL.java.
References org.json.JSONObject.names(), org.json.JSONObject.optJSONObject(), and org.json.CDL.rowToString().
                                                                     {
        JSONObject jo = ja.optJSONObject(0);
        if (jo != null) {
            JSONArray names = jo.names();
            if (names != null) {
                return rowToString(names) + toString(names, ja);
            }
        }
        return null;
    }
static String org.json.CDL.toString (JSONArray names, JSONArray ja) throws JSONException [static]
Produce a comma delimited text from a JSONArray of JSONObjects using a provided list of names. The list of names is not included in the output.
Parameters
names A JSONArray of strings.
ja A JSONArray of JSONObjects.
Returns
A comma delimited text.
Exceptions
JSONException
Definition at line 265 of file CDL.java.
References org.json.JSONObject.append(), org.json.JSONObject.optJSONObject(), org.json.CDL.rowToString(), org.json.JSONObject.toJSONArray(), and org.json.JSONObject.toString().
                                 {
        if (names == null || names.length() == 0) {
            return null;
        }
        StringBuffer sb = new StringBuffer();
        for (int i = 0; i < ja.length(); i += 1) {
            JSONObject jo = ja.optJSONObject(i);
            if (jo != null) {
                sb.append(rowToString(jo.toJSONArray(names)));
            }
        }
        return sb.toString();
    }
The documentation for this class was generated from the following file:
org/json/CDL.java