org.json.JSONWriter Class Reference
Public Member Functions
JSONWriter (Writer w)
JSONWriter array () throws JSONException
JSONWriter endArray () throws JSONException
JSONWriter endObject () throws JSONException
JSONWriter key (String string) throws JSONException
JSONWriter object () throws JSONException
JSONWriter value (boolean b) throws JSONException
JSONWriter value (double d) throws JSONException
JSONWriter value (long l) throws JSONException
JSONWriter value (Object object) throws JSONException
Protected Attributes
char mode
Writer writer
Private Member Functions
JSONWriter append (String string) throws JSONException
JSONWriter end (char mode, char c) throws JSONException
void pop (char c) throws JSONException
void push (JSONObject jo) throws JSONException
Private Attributes
boolean comma
final JSONObject stack []
int top
Static Private Attributes
static final int maxdepth = 200
Detailed Description
JSONWriter provides a quick and convenient way of producing JSON text. The texts produced strictly conform to JSON syntax rules. No whitespace is added, so the results are ready for transmission or storage. Each instance of JSONWriter can produce one JSON text.
A JSONWriter instance provides a value method for appending values to the text, and a key method for adding keys before values in objects. There are array and endArray methods that make and bound array values, and object and endObject methods which make and bound object values. All of these methods return the JSONWriter instance, permitting a cascade style. For example,
new JSONWriter(myWriter)
    .object()
        .key("JSON")
        .value("Hello, World!")
    .endObject();
 which writes
{"JSON":"Hello, World!"}
The first method called must be array or object. There are no methods for adding commas or colons. JSONWriter adds them for you. Objects and arrays can be nested up to 20 levels deep.
This can sometimes be easier than using a JSONObject to build a string.
Author
JSON.org
Version
2011-11-24
Definition at line 59 of file JSONWriter.java.
Constructor & Destructor Documentation
org.json.JSONWriter.JSONWriter (Writer w)
Make a fresh JSONWriter. It can be used to build one JSON text.
Definition at line 96 of file JSONWriter.java.
References org.json.JSONWriter.comma, org.json.JSONWriter.maxdepth, org.json.JSONWriter.mode, org.json.JSONWriter.stack, org.json.JSONWriter.top, and org.json.JSONWriter.writer.
                                {
        this.comma = false;
        this.mode = 'i';
        this.stack = new JSONObject[maxdepth];
        this.top = 0;
        this.writer = w;
    }
Member Function Documentation
JSONWriter org.json.JSONWriter.append (String string) throws JSONException [private]
Append a value.
Parameters
string A string value.
Returns
this
Exceptions
JSONException If the value is out of sequence.
Definition at line 110 of file JSONWriter.java.
References org.json.JSONWriter.comma, org.json.JSONWriter.mode, and org.json.JSONWriter.writer.
Referenced by org.json.JSONWriter.array(), org.json.JSONWriter.object(), and org.json.JSONWriter.value().
                                                                  {
        if (string == null) {
            throw new JSONException("Null pointer");
        }
        if (this.mode == 'o' || this.mode == 'a') {
            try {
                if (this.comma && this.mode == 'a') {
                    this.writer.write(',');
                }
                this.writer.write(string);
            } catch (IOException e) {
                throw new JSONException(e);
            }
            if (this.mode == 'o') {
                this.mode = 'k';
            }
            this.comma = true;
            return this;
        }
        throw new JSONException("Value out of sequence.");
    }
JSONWriter org.json.JSONWriter.array () throws JSONException
Begin appending a new array. All values until the balancing endArray will be appended to this array. The endArray method must be called to mark the array's end.
Returns
this
Exceptions
JSONException If the nesting is too deep, or if the object is started in the wrong place (for example as a key or after the end of the outermost array or object).
Definition at line 141 of file JSONWriter.java.
References org.json.JSONWriter.append(), org.json.JSONWriter.comma, org.json.JSONWriter.mode, and org.json.JSONWriter.push().
                                                   {
        if (this.mode == 'i' || this.mode == 'o' || this.mode == 'a') {
            this.push(null);
            this.append("[");
            this.comma = false;
            return this;
        }
        throw new JSONException("Misplaced array.");
    }
JSONWriter org.json.JSONWriter.end (char mode, char c) throws JSONException [private]
End something.
Parameters
mode Mode
c Closing character
Returns
this
Exceptions
JSONException If unbalanced.
Definition at line 158 of file JSONWriter.java.
References org.json.JSONWriter.comma, org.json.JSONWriter.mode, org.json.JSONWriter.pop(), and org.json.JSONWriter.writer.
Referenced by org.json.JSONWriter.endArray(), and org.json.JSONWriter.endObject().
                                                                   {
        if (this.mode != mode) {
            throw new JSONException(mode == 'a'
                ? "Misplaced endArray."
                : "Misplaced endObject.");
        }
        this.pop(mode);
        try {
            this.writer.write(c);
        } catch (IOException e) {
            throw new JSONException(e);
        }
        this.comma = true;
        return this;
    }
JSONWriter org.json.JSONWriter.endArray () throws JSONException
End an array. This method most be called to balance calls to array.
Returns
this
Exceptions
JSONException If incorrectly nested.
Definition at line 180 of file JSONWriter.java.
References org.json.JSONWriter.end().
                                                      {
        return this.end('a', ']');
    }
JSONWriter org.json.JSONWriter.endObject () throws JSONException
End an object. This method most be called to balance calls to object.
Returns
this
Exceptions
JSONException If incorrectly nested.
Definition at line 190 of file JSONWriter.java.
References org.json.JSONWriter.end().
                                                       {
        return this.end('k', '}');
    }
JSONWriter org.json.JSONWriter.key (String string) throws JSONException
Append a key. The key will be associated with the next value. In an object, every value must be preceded by a key.
Parameters
string A key string.
Returns
this
Exceptions
JSONException If the key is out of place. For example, keys do not belong in arrays or if the key is null.
Definition at line 202 of file JSONWriter.java.
References org.json.JSONWriter.comma, org.json.JSONWriter.mode, org.json.JSONObject.putOnce(), org.json.JSONObject.quote(), org.json.JSONWriter.stack, org.json.JSONWriter.top, and org.json.JSONWriter.writer.
                                                              {
        if (string == null) {
            throw new JSONException("Null key.");
        }
        if (this.mode == 'k') {
            try {
                this.stack[this.top - 1].putOnce(string, Boolean.TRUE);
                if (this.comma) {
                    this.writer.write(',');
                }
                this.writer.write(JSONObject.quote(string));
                this.writer.write(':');
                this.comma = false;
                this.mode = 'o';
                return this;
            } catch (IOException e) {
                throw new JSONException(e);
            }
        }
        throw new JSONException("Misplaced key.");
    }
JSONWriter org.json.JSONWriter.object () throws JSONException
Begin appending a new object. All keys and values until the balancing endObject will be appended to this object. The endObject method must be called to mark the object's end.
Returns
this
Exceptions
JSONException If the nesting is too deep, or if the object is started in the wrong place (for example as a key or after the end of the outermost array or object).
Definition at line 234 of file JSONWriter.java.
References org.json.JSONWriter.append(), org.json.JSONWriter.comma, org.json.JSONWriter.mode, and org.json.JSONWriter.push().
                                                    {
        if (this.mode == 'i') {
            this.mode = 'o';
        }
        if (this.mode == 'o' || this.mode == 'a') {
            this.append("{");
            this.push(new JSONObject());
            this.comma = false;
            return this;
        }
        throw new JSONException("Misplaced object.");
    }
void org.json.JSONWriter.pop (char c) throws JSONException [private]
Pop an array or object scope.
Parameters
c The scope to close.
Exceptions
JSONException If nesting is wrong.
Definition at line 254 of file JSONWriter.java.
References org.json.JSONWriter.mode, org.json.JSONWriter.stack, and org.json.JSONWriter.top.
Referenced by org.json.JSONWriter.end().
                                                  {
        if (this.top <= 0) {
            throw new JSONException("Nesting error.");
        }
        char m = this.stack[this.top - 1] == null ? 'a' : 'k';
        if (m != c) {
            throw new JSONException("Nesting error.");
        }
        this.top -= 1;
        this.mode = this.top == 0
            ? 'd'
            : this.stack[this.top - 1] == null
            ? 'a'
            : 'k';
    }
void org.json.JSONWriter.push (JSONObject jo) throws JSONException [private]
Push an array or object scope.
Parameters
c The scope to open.
Exceptions
JSONException If nesting is too deep.
Definition at line 275 of file JSONWriter.java.
References org.json.JSONWriter.maxdepth, org.json.JSONWriter.mode, org.json.JSONWriter.stack, and org.json.JSONWriter.top.
Referenced by org.json.JSONWriter.array(), and org.json.JSONWriter.object().
                                                          {
        if (this.top >= maxdepth) {
            throw new JSONException("Nesting too deep.");
        }
        this.stack[this.top] = jo;
        this.mode = jo == null ? 'a' : 'k';
        this.top += 1;
    }
JSONWriter org.json.JSONWriter.value (boolean b) throws JSONException
Append either the value true or the value false.
Parameters
b A boolean.
Returns
this
Exceptions
JSONException
Definition at line 292 of file JSONWriter.java.
References org.json.JSONWriter.append().
Referenced by org.json.JSONWriter.value().
                                                            {
        return this.append(b ? "true" : "false");
    }
JSONWriter org.json.JSONWriter.value (double d) throws JSONException
Append a double value.
Parameters
d A double.
Returns
this
Exceptions
JSONException If the number is not finite.
Definition at line 302 of file JSONWriter.java.
References org.json.JSONWriter.value().
                                                           {
        return this.value(new Double(d));
    }
JSONWriter org.json.JSONWriter.value (long l) throws JSONException
Append a long value.
Parameters
l A long.
Returns
this
Exceptions
JSONException
Definition at line 312 of file JSONWriter.java.
References org.json.JSONWriter.append().
                                                         {
        return this.append(Long.toString(l));
    }
JSONWriter org.json.JSONWriter.value (Object object) throws JSONException
Append an object value.
Parameters
object The object to append. It can be null, or a Boolean, Number, String, JSONObject, or JSONArray, or an object that implements JSONString.
Returns
this
Exceptions
JSONException If the value is out of sequence.
Definition at line 324 of file JSONWriter.java.
References org.json.JSONWriter.append(), and org.json.JSONObject.valueToString().
                                                                {
        return this.append(JSONObject.valueToString(object));
    }
Member Data Documentation
boolean org.json.JSONWriter.comma [private]
The comma flag determines if a comma should be output before the next value.
Definition at line 66 of file JSONWriter.java.
Referenced by org.json.JSONWriter.append(), org.json.JSONWriter.array(), org.json.JSONWriter.end(), org.json.JSONWriter.JSONWriter(), org.json.JSONWriter.key(), and org.json.JSONWriter.object().
final int org.json.JSONWriter.maxdepth = 200 [static], [private]
Definition at line 60 of file JSONWriter.java.
Referenced by org.json.JSONWriter.JSONWriter(), and org.json.JSONWriter.push().
char org.json.JSONWriter.mode [protected]
The current mode. Values: 'a' (array), 'd' (done), 'i' (initial), 'k' (key), 'o' (object).
Definition at line 76 of file JSONWriter.java.
Referenced by org.json.JSONWriter.append(), org.json.JSONWriter.array(), org.json.JSONWriter.end(), org.json.JSONWriter.JSONWriter(), org.json.JSONWriter.key(), org.json.JSONWriter.object(), org.json.JSONWriter.pop(), org.json.JSONWriter.push(), and org.json.JSONStringer.toString().
final JSONObject org.json.JSONWriter.stack[] [private]
The object/array stack.
Definition at line 81 of file JSONWriter.java.
Referenced by org.json.JSONWriter.JSONWriter(), org.json.JSONWriter.key(), org.json.JSONWriter.pop(), and org.json.JSONWriter.push().
int org.json.JSONWriter.top [private]
The stack top index. A value of 0 indicates that the stack is empty.
Definition at line 86 of file JSONWriter.java.
Referenced by org.json.JSONWriter.JSONWriter(), org.json.JSONWriter.key(), org.json.JSONWriter.pop(), and org.json.JSONWriter.push().
Writer org.json.JSONWriter.writer [protected]
The writer that will receive the output.
Definition at line 91 of file JSONWriter.java.
Referenced by org.json.JSONWriter.append(), org.json.JSONWriter.end(), org.json.JSONWriter.JSONWriter(), org.json.JSONWriter.key(), and org.json.JSONStringer.toString().
The documentation for this class was generated from the following file:
org/json/JSONWriter.java