org.json.HTTPTokener Class Reference
Public Member Functions
HTTPTokener (String string)
String nextToken () throws JSONException
Additional Inherited Members
Detailed Description
The HTTPTokener extends the JSONTokener to provide additional methods for the parsing of HTTP headers.
Author
JSON.org
Version
2012-11-13
Definition at line 33 of file HTTPTokener.java.
Constructor & Destructor Documentation
org.json.HTTPTokener.HTTPTokener (String string)
Construct an HTTPTokener from a string.
Parameters
string A source string.
Definition at line 39 of file HTTPTokener.java.
                                      {
        super(string);
    }
Member Function Documentation
String org.json.HTTPTokener.nextToken () throws JSONException
Get the next token or string. This is used in parsing HTTP headers.
Exceptions
JSONException
Returns
A String.
Definition at line 49 of file HTTPTokener.java.
References org.json.JSONTokener.next(), and org.json.JSONTokener.syntaxError().
Referenced by org.json.HTTP.toJSONObject().
                                                   {
        char c;
        char q;
        StringBuffer sb = new StringBuffer();
        do {
            c = next();
        } while (Character.isWhitespace(c));
        if (c == '"' || c == '\'') {
            q = c;
            for (;;) {
                c = next();
                if (c < ' ') {
                    throw syntaxError("Unterminated string.");
                }
                if (c == q) {
                    return sb.toString();
                }
                sb.append(c);
            }
        }
        for (;;) {
            if (c == 0 || Character.isWhitespace(c)) {
                return sb.toString();
            }
            sb.append(c);
            c = next();
        }
    }
The documentation for this class was generated from the following file:
org/json/HTTPTokener.java