org.json.JSONArray Class Reference
Public Member Functions
JSONArray ()
JSONArray (JSONTokener x) throws JSONException
JSONArray (String source) throws JSONException
JSONArray (Collection collection)
JSONArray (Object array) throws JSONException
Object get (int index) throws JSONException
boolean getBoolean (int index) throws JSONException
double getDouble (int index) throws JSONException
int getInt (int index) throws JSONException
JSONArray getJSONArray (int index) throws JSONException
JSONObject getJSONObject (int index) throws JSONException
long getLong (int index) throws JSONException
String getString (int index) throws JSONException
boolean isNull (int index)
String join (String separator) throws JSONException
int length ()
Object opt (int index)
boolean optBoolean (int index)
boolean optBoolean (int index, boolean defaultValue)
double optDouble (int index)
double optDouble (int index, double defaultValue)
int optInt (int index)
int optInt (int index, int defaultValue)
JSONArray optJSONArray (int index)
JSONObject optJSONObject (int index)
long optLong (int index)
long optLong (int index, long defaultValue)
String optString (int index)
String optString (int index, String defaultValue)
JSONArray put (boolean value)
JSONArray put (Collection value)
JSONArray put (double value) throws JSONException
JSONArray put (int value)
JSONArray put (long value)
JSONArray put (Map value)
JSONArray put (Object value)
JSONArray put (int index, boolean value) throws JSONException
JSONArray put (int index, Collection value) throws JSONException
JSONArray put (int index, double value) throws JSONException
JSONArray put (int index, int value) throws JSONException
JSONArray put (int index, long value) throws JSONException
JSONArray put (int index, Map value) throws JSONException
JSONArray put (int index, Object value) throws JSONException
Object remove (int index)
JSONObject toJSONObject (JSONArray names) throws JSONException
String toString ()
String toString (int indentFactor) throws JSONException
Writer write (Writer writer) throws JSONException
Package Functions
Writer write (Writer writer, int indentFactor, int indent) throws JSONException
Private Attributes
final ArrayList myArrayList
Detailed Description
A JSONArray is an ordered sequence of values. Its external text form is a string wrapped in square brackets with commas separating the values. The internal form is an object having get and opt methods for accessing the values by index, and put methods for adding or replacing values. The values can be any of these types: Boolean, JSONArray, JSONObject, Number, String, or the JSONObject.NULL object.
The constructor can convert a JSON text into a Java object. The toString method converts to JSON text.
A get method returns a value if one can be found, and throws an exception if one cannot be found. An opt method returns a default value instead of throwing an exception, and so is useful for obtaining optional values.
The generic get() and opt() methods return an object which you can cast or query for type. There are also typed get and opt methods that do type checking and type coercion for you.
The texts produced by the toString methods strictly conform to JSON syntax rules. The constructors are more forgiving in the texts they will accept:
An extra ,
(comma)
may appear just before the closing bracket.
The null value will be inserted when there is ,
(comma)
elision.
Strings may be quoted with '
(single quote)
.
Strings do not need to be quoted at all if they do not begin with a quote or single quote, and if they do not contain leading or trailing spaces, and if they do not contain any of these characters: { } [ ] / \ : , # and if they do not look like numbers and if they are not the reserved words true, false, or null.
Author
JSON.org
Version
2013-04-18
Definition at line 80 of file JSONArray.java.
Constructor & Destructor Documentation
org.json.JSONArray.JSONArray ()
Construct an empty JSONArray.
Definition at line 90 of file JSONArray.java.
References org.json.JSONArray.myArrayList.
Referenced by org.json.JSONArray.optJSONArray(), and org.json.JSONArray.put().
                       {
        this.myArrayList = new ArrayList();
    }
org.json.JSONArray.JSONArray (JSONTokener x) throws JSONException
Construct a JSONArray from a JSONTokener.
Parameters
x A JSONTokener
Exceptions
JSONException If there is a syntax error.
Definition at line 102 of file JSONArray.java.
References org.json.JSONArray.myArrayList, and org.json.JSONObject.NULL.
                                                         {
        this();
        if (x.nextClean() != '[') {
            throw x.syntaxError("A JSONArray text must start with '['");
        }
        if (x.nextClean() != ']') {
            x.back();
            for (;;) {
                if (x.nextClean() == ',') {
                    x.back();
                    this.myArrayList.add(JSONObject.NULL);
                } else {
                    x.back();
                    this.myArrayList.add(x.nextValue());
                }
                switch (x.nextClean()) {
                case ',':
                    if (x.nextClean() == ']') {
                        return;
                    }
                    x.back();
                    break;
                case ']':
                    return;
                default:
                    throw x.syntaxError("Expected a ',' or ']'");
                }
            }
        }
    }
org.json.JSONArray.JSONArray (String source) throws JSONException
Construct a JSONArray from a source JSON text.
Parameters
source A string that begins with [
(left bracket)
and ends with ]
(right bracket)
.
Exceptions
JSONException If there is a syntax error.
Definition at line 143 of file JSONArray.java.
                                                         {
        this(new JSONTokener(source));
    }
org.json.JSONArray.JSONArray (Collection collection)
Construct a JSONArray from a Collection.
Parameters
collection A Collection.
Definition at line 153 of file JSONArray.java.
References org.json.JSONArray.myArrayList, and org.json.JSONObject.wrap().
                                            {
        this.myArrayList = new ArrayList();
        if (collection != null) {
            Iterator iter = collection.iterator();
            while (iter.hasNext()) {
                this.myArrayList.add(JSONObject.wrap(iter.next()));
            }
        }
    }
org.json.JSONArray.JSONArray (Object array) throws JSONException
Construct a JSONArray from an array
Exceptions
JSONException If not an array.
Definition at line 169 of file JSONArray.java.
References org.json.JSONArray.length(), org.json.JSONArray.put(), and org.json.JSONObject.wrap().
                                                        {
        this();
        if (array.getClass().isArray()) {
            int length = Array.getLength(array);
            for (int i = 0; i < length; i += 1) {
                this.put(JSONObject.wrap(Array.get(array, i)));
            }
        } else {
            throw new JSONException(
                    "JSONArray initial value should be a string or collection or array.");
        }
    }
Member Function Documentation
Object org.json.JSONArray.get (int index) throws JSONException
Get the object value associated with an index.
Parameters
index The index must be between 0 and length() - 1.
Returns
An object value.
Exceptions
JSONException If there is no value for the index.
Definition at line 191 of file JSONArray.java.
References org.json.JSONArray.opt().
Referenced by org.json.XML.toString(), and org.json.JSONML.toString().
                                                      {
        Object object = this.opt(index);
        if (object == null) {
            throw new JSONException("JSONArray[" + index + "] not found.");
        }
        return object;
    }
boolean org.json.JSONArray.getBoolean (int index) throws JSONException
Get the boolean value associated with an index. The string values `true` and `false` are converted to boolean.
Parameters
index The index must be between 0 and length() - 1.
Returns
The truth.
Exceptions
JSONException If there is no value for the index or if the value is not convertible to boolean.
Definition at line 210 of file JSONArray.java.
Referenced by org.json.JSONArray.optBoolean().
                                                              {
        Object object = this.get(index);
        if (object.equals(Boolean.FALSE)
                || (object instanceof String && ((String) object)
                        .equalsIgnoreCase("false"))) {
            return false;
        } else if (object.equals(Boolean.TRUE)
                || (object instanceof String && ((String) object)
                        .equalsIgnoreCase("true"))) {
            return true;
        }
        throw new JSONException("JSONArray[" + index + "] is not a boolean.");
    }
double org.json.JSONArray.getDouble (int index) throws JSONException
Get the double value associated with an index.
Parameters
index The index must be between 0 and length() - 1.
Returns
The value.
Exceptions
JSONException If the key is not found or if the value cannot be converted to a number.
Definition at line 234 of file JSONArray.java.
Referenced by org.json.JSONArray.optDouble().
                                                            {
        Object object = this.get(index);
        try {
            return object instanceof Number ? ((Number) object).doubleValue()
                    : Double.parseDouble((String) object);
        } catch (Exception e) {
            throw new JSONException("JSONArray[" + index + "] is not a number.");
        }
    }
int org.json.JSONArray.getInt (int index) throws JSONException
Get the int value associated with an index.
Parameters
index The index must be between 0 and length() - 1.
Returns
The value.
Exceptions
JSONException If the key is not found or if the value is not a number.
Definition at line 253 of file JSONArray.java.
Referenced by org.json.JSONArray.optInt().
                                                      {
        Object object = this.get(index);
        try {
            return object instanceof Number ? ((Number) object).intValue()
                    : Integer.parseInt((String) object);
        } catch (Exception e) {
            throw new JSONException("JSONArray[" + index + "] is not a number.");
        }
    }
JSONArray org.json.JSONArray.getJSONArray (int index) throws JSONException
Get the JSONArray associated with an index.
Parameters
index The index must be between 0 and length() - 1.
Returns
A JSONArray value.
Exceptions
JSONException If there is no value for the index. or if the value is not a JSONArray
Definition at line 273 of file JSONArray.java.
                                                                  {
        Object object = this.get(index);
        if (object instanceof JSONArray) {
            return (JSONArray) object;
        }
        throw new JSONException("JSONArray[" + index + "] is not a JSONArray.");
    }
JSONObject org.json.JSONArray.getJSONObject (int index) throws JSONException
Get the JSONObject associated with an index.
Parameters
index subscript
Returns
A JSONObject value.
Exceptions
JSONException If there is no value for the index or if the value is not a JSONObject
Definition at line 291 of file JSONArray.java.
Referenced by org.facebook.crawler.FacebookJsonParser.crawlGroup(), org.facebook.crawler.FacebookJsonParser.crawlUser(), and JsonReader.main().
                                                                    {
        Object object = this.get(index);
        if (object instanceof JSONObject) {
            return (JSONObject) object;
        }
        throw new JSONException("JSONArray[" + index + "] is not a JSONObject.");
    }
long org.json.JSONArray.getLong (int index) throws JSONException
Get the long value associated with an index.
Parameters
index The index must be between 0 and length() - 1.
Returns
The value.
Exceptions
JSONException If the key is not found or if the value cannot be converted to a number.
Definition at line 309 of file JSONArray.java.
Referenced by org.json.JSONArray.optLong().
                                                        {
        Object object = this.get(index);
        try {
            return object instanceof Number ? ((Number) object).longValue()
                    : Long.parseLong((String) object);
        } catch (Exception e) {
            throw new JSONException("JSONArray[" + index + "] is not a number.");
        }
    }
String org.json.JSONArray.getString (int index) throws JSONException
Get the string associated with an index.
Parameters
index The index must be between 0 and length() - 1.
Returns
A string value.
Exceptions
JSONException If there is no string value for the index.
Definition at line 328 of file JSONArray.java.
Referenced by org.facebook.crawler.FacebookJsonParser.crawlUser(), JsonReader.main(), and org.json.JSONObject.toJSONArray().
                                                            {
        Object object = this.get(index);
        if (object instanceof String) {
            return (String) object;
        }
        throw new JSONException("JSONArray[" + index + "] not a string.");
    }
boolean org.json.JSONArray.isNull (int index)
Determine if the value is null.
Parameters
index The index must be between 0 and length() - 1.
Returns
true if the value at the index is null, or if there is no value.
Definition at line 343 of file JSONArray.java.
References org.json.JSONObject.NULL, and org.json.JSONArray.opt().
                                     {
        return JSONObject.NULL.equals(this.opt(index));
    }
String org.json.JSONArray.join (String separator) throws JSONException
Make a string from the contents of this JSONArray. The separator string is inserted between each element. Warning: This method assumes that the data structure is acyclical.
Parameters
separator A string that will be inserted between the elements.
Returns
a string.
Exceptions
JSONException If the array contains an invalid number.
Definition at line 358 of file JSONArray.java.
References org.json.JSONArray.length(), and org.json.JSONObject.valueToString().
                                                              {
        int len = this.length();
        StringBuffer sb = new StringBuffer();
        for (int i = 0; i < len; i += 1) {
            if (i > 0) {
                sb.append(separator);
            }
            sb.append(JSONObject.valueToString(this.myArrayList.get(i)));
        }
        return sb.toString();
    }
int org.json.JSONArray.length ()
Get the number of elements in the JSONArray, included nulls.
Returns
The length (or size).
Definition at line 376 of file JSONArray.java.
References org.json.JSONArray.myArrayList.
Referenced by org.facebook.crawler.FacebookJsonParser.crawlGroup(), org.facebook.crawler.FacebookJsonParser.crawlUser(), org.json.JSONArray.join(), org.json.JSONArray.JSONArray(), JsonReader.main(), org.json.JSONObject.names(), org.json.JSONArray.opt(), org.json.JSONML.parse(), org.json.JSONArray.put(), org.json.CDL.rowToJSONArray(), org.json.CDL.rowToString(), org.json.CDL.toJSONArray(), org.json.JSONObject.toJSONArray(), org.json.JSONArray.toJSONObject(), org.json.XML.toString(), org.json.JSONML.toString(), and org.json.JSONArray.write().
                        {
        return this.myArrayList.size();
    }
Object org.json.JSONArray.opt (int index)
Get the optional object value associated with an index.
Parameters
index The index must be between 0 and length() - 1.
Returns
An object value, or null if there is no object at that index.
Definition at line 387 of file JSONArray.java.
References org.json.JSONArray.length(), and org.json.JSONArray.myArrayList.
Referenced by org.json.JSONArray.get(), org.json.JSONArray.isNull(), org.json.JSONArray.optJSONArray(), org.json.JSONArray.optJSONObject(), org.json.JSONArray.optString(), org.json.JSONArray.remove(), org.json.CDL.rowToString(), org.json.JSONArray.toJSONObject(), and org.json.XML.toString().
                                 {
        return (index < 0 || index >= this.length()) ? null : this.
      myArrayList
                .get(index);
    }
boolean org.json.JSONArray.optBoolean (int index)
Get the optional boolean value associated with an index. It returns false if there is no value at that index, or if the value is not Boolean.TRUE or the String `true`.
Parameters
index The index must be between 0 and length() - 1.
Returns
The truth.
Definition at line 401 of file JSONArray.java.
                                         {
        return this.optBoolean(index, false);
    }
boolean org.json.JSONArray.optBoolean (int index, boolean defaultValue)
Get the optional boolean value associated with an index. It returns the defaultValue if there is no value at that index or if it is not a Boolean or the String `true` or `false` (case insensitive).
Parameters
index The index must be between 0 and length() - 1.
defaultValue A boolean default.
Returns
The truth.
Definition at line 416 of file JSONArray.java.
References org.json.JSONArray.getBoolean().
                                                               {
        try {
            return this.getBoolean(index);
        } catch (Exception e) {
            return defaultValue;
        }
    }
double org.json.JSONArray.optDouble (int index)
Get the optional double value associated with an index. NaN is returned if there is no value for the index, or if the value is not a number and cannot be converted to a number.
Parameters
index The index must be between 0 and length() - 1.
Returns
The value.
Definition at line 433 of file JSONArray.java.
                                       {
        return this.optDouble(index, Double.NaN);
    }
double org.json.JSONArray.optDouble (int index, double defaultValue)
Get the optional double value associated with an index. The defaultValue is returned if there is no value for the index, or if the value is not a number and cannot be converted to a number.
Parameters
index subscript
defaultValue The default value.
Returns
The value.
Definition at line 448 of file JSONArray.java.
References org.json.JSONArray.getDouble().
                                                            {
        try {
            return this.getDouble(index);
        } catch (Exception e) {
            return defaultValue;
        }
    }
int org.json.JSONArray.optInt (int index)
Get the optional int value associated with an index. Zero is returned if there is no value for the index, or if the value is not a number and cannot be converted to a number.
Parameters
index The index must be between 0 and length() - 1.
Returns
The value.
Definition at line 465 of file JSONArray.java.
                                 {
        return this.optInt(index, 0);
    }
int org.json.JSONArray.optInt (int index, int defaultValue)
Get the optional int value associated with an index. The defaultValue is returned if there is no value for the index, or if the value is not a number and cannot be converted to a number.
Parameters
index The index must be between 0 and length() - 1.
defaultValue The default value.
Returns
The value.
Definition at line 480 of file JSONArray.java.
References org.json.JSONArray.getInt().
                                                   {
        try {
            return this.getInt(index);
        } catch (Exception e) {
            return defaultValue;
        }
    }
JSONArray org.json.JSONArray.optJSONArray (int index)
Get the optional JSONArray associated with an index.
Parameters
index subscript
Returns
A JSONArray value, or null if the index has no value, or if the value is not a JSONArray.
Definition at line 496 of file JSONArray.java.
References org.json.JSONArray.JSONArray(), and org.json.JSONArray.opt().
Referenced by org.json.JSONML.toString().
                                             {
        Object o = this.opt(index);
        return o instanceof JSONArray ? (JSONArray) o : null;
    }
JSONObject org.json.JSONArray.optJSONObject (int index)
Get the optional JSONObject associated with an index. Null is returned if the key is not found, or null if the index has no value, or if the value is not a JSONObject.
Parameters
index The index must be between 0 and length() - 1.
Returns
A JSONObject value.
Definition at line 510 of file JSONArray.java.
References org.json.JSONArray.opt().
                                               {
        Object o = this.opt(index);
        return o instanceof JSONObject ? (JSONObject) o : null;
    }
long org.json.JSONArray.optLong (int index)
Get the optional long value associated with an index. Zero is returned if there is no value for the index, or if the value is not a number and cannot be converted to a number.
Parameters
index The index must be between 0 and length() - 1.
Returns
The value.
Definition at line 524 of file JSONArray.java.
                                   {
        return this.optLong(index, 0);
    }
long org.json.JSONArray.optLong (int index, long defaultValue)
Get the optional long value associated with an index. The defaultValue is returned if there is no value for the index, or if the value is not a number and cannot be converted to a number.
Parameters
index The index must be between 0 and length() - 1.
defaultValue The default value.
Returns
The value.
Definition at line 539 of file JSONArray.java.
References org.json.JSONArray.getLong().
                                                      {
        try {
            return this.getLong(index);
        } catch (Exception e) {
            return defaultValue;
        }
    }
String org.json.JSONArray.optString (int index)
Get the optional string value associated with an index. It returns an empty string if there is no value at that index. If the value is not a string and is not null, then it is coverted to a string.
Parameters
index The index must be between 0 and length() - 1.
Returns
A String value.
Definition at line 556 of file JSONArray.java.
Referenced by org.json.JSONML.toString().
                                       {
        return this.optString(index, "");
    }
String org.json.JSONArray.optString (int index, String defaultValue)
Get the optional string associated with an index. The defaultValue is returned if the key is not found.
Parameters
index The index must be between 0 and length() - 1.
defaultValue The default value.
Returns
A String value.
Definition at line 570 of file JSONArray.java.
References org.json.JSONObject.NULL, and org.json.JSONArray.opt().
                                                            {
        Object object = this.opt(index);
        return JSONObject.NULL.equals(object) ? defaultValue : object
                .toString();
    }
JSONArray org.json.JSONArray.put (boolean value)
Append a boolean value. This increases the array's length by one.
Parameters
value A boolean value.
Returns
this.
Definition at line 583 of file JSONArray.java.
Referenced by org.json.JSONArray.JSONArray(), org.json.JSONObject.names(), org.json.JSONML.parse(), org.json.JSONArray.put(), org.json.CDL.rowToJSONArray(), org.json.CDL.toJSONArray(), and org.json.JSONObject.toJSONArray().
                                        {
        this.put(value ? Boolean.TRUE : Boolean.FALSE);
        return this;
    }
JSONArray org.json.JSONArray.put (Collection value)
Put a value in the JSONArray, where the value will be a JSONArray which is produced from a Collection.
Parameters
value A Collection value.
Returns
this.
Definition at line 596 of file JSONArray.java.
References org.json.JSONArray.JSONArray(), and org.json.JSONArray.put().
                                           {
        this.put(new JSONArray(value));
        return this;
    }
JSONArray org.json.JSONArray.put (double value) throws JSONException
Append a double value. This increases the array's length by one.
Parameters
value A double value.
Exceptions
JSONException if the value is not finite.
Returns
this.
Definition at line 610 of file JSONArray.java.
References org.json.JSONArray.put(), and org.json.JSONObject.testValidity().
                                                            {
        Double d = new Double(value);
        JSONObject.testValidity(d);
        this.put(d);
        return this;
    }
JSONArray org.json.JSONArray.put (int value)
Append an int value. This increases the array's length by one.
Parameters
value An int value.
Returns
this.
Definition at line 624 of file JSONArray.java.
References org.json.JSONArray.put().
                                    {
        this.put(new Integer(value));
        return this;
    }
JSONArray org.json.JSONArray.put (long value)
Append an long value. This increases the array's length by one.
Parameters
value A long value.
Returns
this.
Definition at line 636 of file JSONArray.java.
References org.json.JSONArray.put().
                                     {
        this.put(new Long(value));
        return this;
    }
JSONArray org.json.JSONArray.put (Map value)
Put a value in the JSONArray, where the value will be a JSONObject which is produced from a Map.
Parameters
value A Map value.
Returns
this.
Definition at line 649 of file JSONArray.java.
References org.json.JSONArray.put().
                                    {
        this.put(new JSONObject(value));
        return this;
    }
JSONArray org.json.JSONArray.put (Object value)
Append an object value. This increases the array's length by one.
Parameters
value An object value. The value should be a Boolean, Double, Integer, JSONArray, JSONObject, Long, or String, or the JSONObject.NULL object.
Returns
this.
Definition at line 663 of file JSONArray.java.
References org.json.JSONArray.myArrayList.
                                       {
        this.myArrayList.add(value);
        return this;
    }
JSONArray org.json.JSONArray.put (int index, boolean value) throws JSONException
Put or replace a boolean value in the JSONArray. If the index is greater than the length of the JSONArray, then null elements will be added as necessary to pad it out.
Parameters
index The subscript.
value A boolean value.
Returns
this.
Exceptions
JSONException If the index is negative.
Definition at line 681 of file JSONArray.java.
References org.json.JSONArray.put().
                                                                        {
        this.put(index, value ? Boolean.TRUE : Boolean.FALSE);
        return this;
    }
JSONArray org.json.JSONArray.put (int index, Collection value) throws JSONException
Put a value in the JSONArray, where the value will be a JSONArray which is produced from a Collection.
Parameters
index The subscript.
value A Collection value.
Returns
this.
Exceptions
JSONException If the index is negative or if the value is not finite.
Definition at line 698 of file JSONArray.java.
References org.json.JSONArray.JSONArray(), and org.json.JSONArray.put().
                                                                           {
        this.put(index, new JSONArray(value));
        return this;
    }
JSONArray org.json.JSONArray.put (int index, double value) throws JSONException
Put or replace a double value. If the index is greater than the length of the JSONArray, then null elements will be added as necessary to pad it out.
Parameters
index The subscript.
value A double value.
Returns
this.
Exceptions
JSONException If the index is negative or if the value is not finite.
Definition at line 716 of file JSONArray.java.
References org.json.JSONArray.put().
                                                                       {
        this.put(index, new Double(value));
        return this;
    }
JSONArray org.json.JSONArray.put (int index, int value) throws JSONException
Put or replace an int value. If the index is greater than the length of the JSONArray, then null elements will be added as necessary to pad it out.
Parameters
index The subscript.
value An int value.
Returns
this.
Exceptions
JSONException If the index is negative.
Definition at line 734 of file JSONArray.java.
References org.json.JSONArray.put().
                                                                    {
        this.put(index, new Integer(value));
        return this;
    }
JSONArray org.json.JSONArray.put (int index, long value) throws JSONException
Put or replace a long value. If the index is greater than the length of the JSONArray, then null elements will be added as necessary to pad it out.
Parameters
index The subscript.
value A long value.
Returns
this.
Exceptions
JSONException If the index is negative.
Definition at line 752 of file JSONArray.java.
References org.json.JSONArray.put().
                                                                     {
        this.put(index, new Long(value));
        return this;
    }
JSONArray org.json.JSONArray.put (int index, Map value) throws JSONException
Put a value in the JSONArray, where the value will be a JSONObject that is produced from a Map.
Parameters
index The subscript.
value The Map value.
Returns
this.
Exceptions
JSONException If the index is negative or if the the value is an invalid number.
Definition at line 770 of file JSONArray.java.
References org.json.JSONArray.put().
                                                                    {
        this.put(index, new JSONObject(value));
        return this;
    }
JSONArray org.json.JSONArray.put (int index, Object value) throws JSONException
Put or replace an object value in the JSONArray. If the index is greater than the length of the JSONArray, then null elements will be added as necessary to pad it out.
Parameters
index The subscript.
value The value to put into the array. The value should be a Boolean, Double, Integer, JSONArray, JSONObject, Long, or String, or the JSONObject.NULL object.
Returns
this.
Exceptions
JSONException If the index is negative or if the the value is an invalid number.
Definition at line 791 of file JSONArray.java.
References org.json.JSONArray.length(), org.json.JSONArray.myArrayList, org.json.JSONObject.NULL, org.json.JSONArray.put(), and org.json.JSONObject.testValidity().
                                                                       {
        JSONObject.testValidity(value);
        if (index < 0) {
            throw new JSONException("JSONArray[" + index + "] not found.");
        }
        if (index < this.length()) {
            this.myArrayList.set(index, value);
        } else {
            while (index != this.length()) {
                this.put(JSONObject.NULL);
            }
            this.put(value);
        }
        return this;
    }
Object org.json.JSONArray.remove (int index)
Remove an index and close the hole.
Parameters
index The index of the element to be removed.
Returns
The value that was associated with the index, or null if there was no value.
Definition at line 815 of file JSONArray.java.
References org.json.JSONArray.myArrayList, and org.json.JSONArray.opt().
                                    {
        Object o = this.opt(index);
        this.myArrayList.remove(index);
        return o;
    }
JSONObject org.json.JSONArray.toJSONObject (JSONArray names) throws JSONException
Produce a JSONObject by combining a JSONArray of names with the values of this JSONArray.
Parameters
names A JSONArray containing a list of key strings. These will be paired with the values.
Returns
A JSONObject, or null if there are no names or if this JSONArray has no values.
Exceptions
JSONException If any of the names are null.
Definition at line 833 of file JSONArray.java.
References org.json.JSONArray.length(), org.json.JSONArray.opt(), and org.json.JSONObject.put().
Referenced by org.json.CDL.rowToJSONObject().
                                                                         {
        if (names == null || names.length() == 0 || this.length() == 0) {
            return null;
        }
        JSONObject jo = new JSONObject();
        for (int i = 0; i < names.length(); i += 1) {
            jo.put(names.getString(i), this.opt(i));
        }
        return jo;
    }
String org.json.JSONArray.toString ()
Make a JSON text of this JSONArray. For compactness, no unnecessary whitespace is added. If it is not possible to produce a syntactically correct JSON text then null will be returned instead. This could occur if the array contains an invalid number.
Warning: This method assumes that the data structure is acyclical.
Returns
a printable, displayable, transmittable representation of the array.
Definition at line 855 of file JSONArray.java.
                             {
        try {
            return this.toString(0);
        } catch (Exception e) {
            return null;
        }
    }
String org.json.JSONArray.toString (int indentFactor) throws JSONException
Make a prettyprinted JSON text of this JSONArray. Warning: This method assumes that the data structure is acyclical.
Parameters
indentFactor The number of spaces to add to each level of indentation.
Returns
a printable, displayable, transmittable representation of the object, beginning with [
(left bracket)
and ending with ]
(right bracket)
.
Exceptions
JSONException
Definition at line 875 of file JSONArray.java.
References org.json.JSONArray.write().
                                                                  {
        StringWriter sw = new StringWriter();
        synchronized (sw.getBuffer()) {
            return this.write(sw, indentFactor, 0).toString();
        }
    }
Writer org.json.JSONArray.write (Writer writer) throws JSONException
Write the contents of the JSONArray as JSON text to a writer. For compactness, no whitespace is added.
Warning: This method assumes that the data structure is acyclical.
Returns
The writer.
Exceptions
JSONException
Definition at line 891 of file JSONArray.java.
Referenced by org.json.JSONArray.toString().
                                                            {
        return this.write(writer, 0, 0);
    }
Writer org.json.JSONArray.write (Writer writer, int indentFactor, int indent) throws JSONException [package]
Write the contents of the JSONArray as JSON text to a writer. For compactness, no whitespace is added.
Warning: This method assumes that the data structure is acyclical.
Parameters
indentFactor The number of spaces to add to each level of indentation.
indent The indention of the top level.
Returns
The writer.
Exceptions
JSONException
Definition at line 908 of file JSONArray.java.
References org.json.JSONObject.indent(), org.json.JSONArray.length(), org.json.JSONArray.myArrayList, and org.json.JSONObject.writeValue().
                                 {
        try {
            boolean commanate = false;
            int length = this.length();
            writer.write('[');
            if (length == 1) {
                JSONObject.writeValue(writer, this.myArrayList.get(0),
                        indentFactor, indent);
            } else if (length != 0) {
                final int newindent = indent + indentFactor;
                for (int i = 0; i < length; i += 1) {
                    if (commanate) {
                        writer.write(',');
                    }
                    if (indentFactor > 0) {
                        writer.write('\n');
                    }
                    JSONObject.indent(writer, newindent);
                    JSONObject.writeValue(writer, this.myArrayList.get(i),
                            indentFactor, newindent);
                    commanate = true;
                }
                if (indentFactor > 0) {
                    writer.write('\n');
                }
                JSONObject.indent(writer, indent);
            }
            writer.write(']');
            return writer;
        } catch (IOException e) {
            throw new JSONException(e);
        }
    }
Member Data Documentation
final ArrayList org.json.JSONArray.myArrayList [private]
The arrayList where the JSONArray's properties are kept.
Definition at line 85 of file JSONArray.java.
Referenced by org.json.JSONArray.JSONArray(), org.json.JSONArray.length(), org.json.JSONArray.opt(), org.json.JSONArray.put(), org.json.JSONArray.remove(), and org.json.JSONArray.write().
The documentation for this class was generated from the following file:
org/json/JSONArray.java