org.json.Kim Class Reference
Public Member Functions
Kim (byte[] bytes, int from, int thru)
Kim (byte[] bytes, int length)
Kim (Kim kim, int from, int thru)
Kim (String string) throws JSONException
int characterAt (int at) throws JSONException
int copy (byte[] bytes, int at)
boolean equals (Object obj)
int get (int at) throws JSONException
int hashCode ()
String toString () throws JSONException
Static Public Member Functions
static int characterSize (int character) throws JSONException
Public Attributes
int length = 0
Private Attributes
byte[] bytes = null
int hashcode = 0
String string = null
Detailed Description
Kim makes immutable eight bit Unicode strings. If the MSB of a byte is set, then the next byte is a continuation byte. The last byte of a character never has the MSB reset. Every byte that is not the last byte has the MSB set. Kim stands for `Keep it minimal`. A Unicode character is never longer than 3 bytes. Every byte contributes 7 bits to the character. ASCII is unmodified.
             Kim             UTF-8
 one byte U+007F U+007F two bytes U+3FFF U+07FF three bytes U+10FFF U+FFFF four bytes U+10FFFF
Characters in the ranges U+0800..U+3FFF and U+10000..U+10FFFF will be one byte smaller when encoded in Kim compared to UTF-8.
Kim is beneficial when using scripts such as Old South Arabian, Aramaic, Avestan, Balinese, Batak, Bopomofo, Buginese, Buhid, Carian, Cherokee, Coptic, Cyrillic, Deseret, Egyptian Hieroglyphs, Ethiopic, Georgian, Glagolitic, Gothic, Hangul Jamo, Hanunoo, Hiragana, Kanbun, Kaithi, Kannada, Katakana, Kharoshthi, Khmer, Lao, Lepcha, Limbu, Lycian, Lydian, Malayalam, Mandaic, Meroitic, Miao, Mongolian, Myanmar, New Tai Lue, Ol Chiki, Old Turkic, Oriya, Osmanya, Pahlavi, Parthian, Phags-Pa, Phoenician, Samaritan, Sharada, Sinhala, Sora Sompeng, Tagalog, Tagbanwa, Takri, Tai Le, Tai Tham, Tamil, Telugu, Thai, Tibetan, Tifinagh, UCAS.
A kim object can be constructed from an ordinary UTF-16 string, or from a byte array. A kim object can produce a UTF-16 string.
As with UTF-8, it is possible to detect character boundaries within a byte sequence. UTF-8 is one of the world's great inventions. While Kim is more efficient, it is not clear that it is worth the expense of transition.
Version
2013-04-18
Definition at line 64 of file Kim.java.
Constructor & Destructor Documentation
org.json.Kim.Kim (byte[] bytes, int from, int thru)
Make a kim from a portion of a byte array.
Parameters
bytes A byte array.
from The index of the first byte.
thru The index of the last byte plus one.
Definition at line 97 of file Kim.java.
References org.json.Kim.hashcode, and org.json.Kim.length.
Referenced by org.json.Kim.equals().
                                                 {
// As the bytes are copied into the new kim, a hashcode is computed using a
// modified Fletcher code.
        int sum = 1;
        int value;
        this.hashcode = 0;
        this.length = thru - from;
        if (this.length > 0) {
            this.bytes = new byte[this.length];
            for (int at = 0; at < this.length; at += 1) {
                value = (int) bytes[at + from] & 0xFF;
                sum += value;
                this.hashcode += sum;
                this.bytes[at] = (byte) value;
            }
            this.hashcode += sum << 16;
        }
    }
org.json.Kim.Kim (byte[] bytes, int length)
Make a kim from a byte array.
Parameters
bytes The byte array.
length The number of bytes.
Definition at line 126 of file Kim.java.
References org.json.Kim.bytes, and org.json.Kim.length.
                                         {
        this(bytes, 0, length);
    }
org.json.Kim.Kim (Kim kim, int from, int thru)
Make a new kim from a substring of an existing kim. The coordinates are in byte units, not character units.
Parameters
kim The source of bytes.
from The point at which to take bytes.
thru The point at which to stop taking bytes.
Returns
the substring
Definition at line 142 of file Kim.java.
References org.json.Kim.bytes.
                                            {
        this(kim.bytes, from, thru);
    }
org.json.Kim.Kim (String string) throws JSONException
Make a kim from a string.
Parameters
string The string.
Exceptions
JSONException if surrogate pair mismatch.
Definition at line 154 of file Kim.java.
References org.json.Kim.bytes, org.json.Kim.hashcode, and org.json.Kim.length.
                                                   {
        int stringLength = string.length();
        this.hashcode = 0;
        this.length = 0;
// First pass: Determine the length of the kim, allowing for the UTF-16
// to UTF-32 conversion, and then the UTF-32 to Kim conversion.
        if (stringLength > 0) {
            for (int i = 0; i < stringLength; i += 1) {
                int c = string.charAt(i);
                if (c <= 0x7F) {
                    this.length += 1;
                } else if (c <= 0x3FFF) {
                    this.length += 2;
                } else {
                    if (c >= 0xD800 && c <= 0xDFFF) {
                        i += 1;
                        int d = string.charAt(i);
                        if (c > 0xDBFF || d < 0xDC00 || d > 0xDFFF) {
                            throw new JSONException("Bad UTF16");
                        }
                    }
                    this.length += 3;
                }
            }
// Second pass: Allocate a byte array and fill that array with the conversion
// while computing the hashcode.
            this.bytes = new byte[length];
            int at = 0;
            int b;
            int sum = 1;
            for (int i = 0; i < stringLength; i += 1) {
                int character = string.charAt(i);
                if (character <= 0x7F) {
                    bytes[at] = (byte) character;
                    sum += character;
                    this.hashcode += sum;
                    at += 1;
                } else if (character <= 0x3FFF) {
                    b = 0x80 | (character >>> 7);
                    bytes[at] = (byte) b;
                    sum += b;
                    this.hashcode += sum;
                    at += 1;
                    b = character & 0x7F;
                    bytes[at] = (byte) b;
                    sum += b;
                    this.hashcode += sum;
                    at += 1;
                } else {
                    if (character >= 0xD800 && character <= 0xDBFF) {
                        i += 1;
                        character = (((character & 0x3FF) << 10) | (string
                                .charAt(i) & 0x3FF)) + 65536;
                    }
                    b = 0x80 | (character >>> 14);
                    bytes[at] = (byte) b;
                    sum += b;
                    this.hashcode += sum;
                    at += 1;
                    b = 0x80 | ((character >>> 7) & 0xFF);
                    bytes[at] = (byte) b;
                    sum += b;
                    this.hashcode += sum;
                    at += 1;
                    b = character & 0x7F;
                    bytes[at] = (byte) b;
                    sum += b;
                    this.hashcode += sum;
                    at += 1;
                }
            }
            this.hashcode += sum << 16;
        }
    }
Member Function Documentation
int org.json.Kim.characterAt (int at) throws JSONException
Returns the character at the specified index. The index refers to byte values and ranges from 0 to length - 1. The index of the next character is at index + Kim.characterSize(kim.characterAt(index)).
Parameters
at the index of the char value. The first character is at 0.
Returns
a Unicode character between 0 and 0x10FFFF.
Exceptions
JSONException if at does not point to a valid character.
Definition at line 244 of file Kim.java.
Referenced by org.json.Kim.toString().
                                                        {
        int c = get(at);
        if ((c & 0x80) == 0) {
            return c;
        }
        int character;
        int c1 = get(at + 1);
        if ((c1 & 0x80) == 0) {
            character = ((c & 0x7F) << 7) | c1;
            if (character > 0x7F) {
                return character;
            }
        } else {
            int c2 = get(at + 2);
            character = ((c & 0x7F) << 14) | ((c1 & 0x7F) << 7) | c2;
            if ((c2 & 0x80) == 0 && character > 0x3FFF && character <= 0x10FFFF
                    && (character < 0xD800 || character > 0xDFFF)) {
                return character;
            }
        }
        throw new JSONException("Bad character at " + at);
    }
static int org.json.Kim.characterSize (int character) throws JSONException [static]
Returns the number of bytes needed to contain the character in Kim format.
Parameters
character a Unicode character between 0 and 0x10FFFF.
Returns
1, 2, or 3
Exceptions
JSONException if the character is not representable in a kim.
Definition at line 277 of file Kim.java.
Referenced by org.json.Kim.toString().
                                                                        {
        if (character < 0 || character > 0x10FFFF) {
            throw new JSONException("Bad character " + character);
        }
        return character <= 0x7F ? 1 : character <= 0x3FFF ? 2 : 3;
    }
int org.json.Kim.copy (byte[] bytes, int at)
Copy the contents of this kim to a byte array.
Parameters
bytes A byte array of sufficient size.
at The position within the byte array to take the byes.
Returns
The position immediately after the copy.
Definition at line 293 of file Kim.java.
References org.json.Kim.length.
                                          {
        System.arraycopy(this.bytes, 0, bytes, at, this.length);
        return at + this.length;
    }
boolean org.json.Kim.equals (Object obj)
Two kim objects containing exactly the same bytes in the same order are equal to each other.
Parameters
obj the other kim with which to compare.
Returns
true if this and obj are both kim objects containing identical byte sequences.
Definition at line 307 of file Kim.java.
References org.json.Kim.bytes, org.json.Kim.hashcode, and org.json.Kim.Kim().
                                      {
        if (!(obj instanceof Kim)) {
            return false;
        }
        Kim that = (Kim) obj;
        if (this == that) {
            return true;
        }
        if (this.hashcode != that.hashcode) {
            return false;
        }
        return java.util.Arrays.equals(this.bytes, that.bytes);
    }
int org.json.Kim.get (int at) throws JSONException
Get a byte from a kim.
Parameters
at The position of the byte. The first byte is at 0.
Returns
The byte.
Exceptions
JSONException if there is no byte at that position.
Definition at line 329 of file Kim.java.
References org.json.Kim.bytes, and org.json.Kim.length.
                                                {
        if (at < 0 || at > this.length) {
            throw new JSONException("Bad character at " + at);
        }
        return ((int) this.bytes[at]) & 0xFF;
    }
int org.json.Kim.hashCode ()
Returns a hash code value for the kim.
Definition at line 339 of file Kim.java.
References org.json.Kim.hashcode.
                          {
        return this.hashcode;
    }
String org.json.Kim.toString () throws JSONException
Produce a UTF-16 String from this kim. The number of codepoints in the string will not be greater than the number of bytes in the kim, although it could be less.
Returns
The string. A kim memoizes its string representation.
Exceptions
JSONException if the kim is not valid.
Definition at line 352 of file Kim.java.
References org.json.Kim.characterAt(), org.json.Kim.characterSize(), org.json.Kim.length, and org.json.Kim.string.
                                                  {
        if (this.string == null) {
            int c;
            int length = 0;
            char chars[] = new char[this.length];
            for (int at = 0; at < this.length; at += characterSize(c)) {
                c = this.characterAt(at);
                if (c < 0x10000) {
                    chars[length] = (char) c;
                    length += 1;
                } else {
                    chars[length] = (char) (0xD800 | ((c - 0x10000) >>> 10));
                    length += 1;
                    chars[length] = (char) (0xDC00 | (c & 0x03FF));
                    length += 1;
                }
            }
            this.string = new String(chars, 0, length);
        }
        return this.string;
    }
Member Data Documentation
byte [] org.json.Kim.bytes = null [private]
The byte array containing the kim's content.
Definition at line 69 of file Kim.java.
Referenced by org.json.Kim.equals(), org.json.Kim.get(), and org.json.Kim.Kim().
int org.json.Kim.hashcode = 0 [private]
The kim's hashcode, conforming to Java's hashcode conventions.
Definition at line 74 of file Kim.java.
Referenced by org.json.Kim.equals(), org.json.Kim.hashCode(), and org.json.Kim.Kim().
int org.json.Kim.length = 0
The number of bytes in the kim. The number of bytes can be as much as three times the number of characters.
Definition at line 80 of file Kim.java.
Referenced by org.json.Kim.copy(), org.json.Kim.get(), org.json.Kim.Kim(), and org.json.Kim.toString().
String org.json.Kim.string = null [private]
The memoization of toString().
Definition at line 85 of file Kim.java.
Referenced by org.json.Kim.toString().
The documentation for this class was generated from the following file:
org/json/Kim.java