org.json.JSONTokener Class Reference
Public Member Functions
JSONTokener (Reader reader)
JSONTokener (InputStream inputStream) throws JSONException
JSONTokener (String s)
void back () throws JSONException
boolean end ()
boolean more () throws JSONException
char next () throws JSONException
char next (char c) throws JSONException
String next (int n) throws JSONException
char nextClean () throws JSONException
String nextString (char quote) throws JSONException
String nextTo (char delimiter) throws JSONException
String nextTo (String delimiters) throws JSONException
Object nextValue () throws JSONException
char skipTo (char to) throws JSONException
JSONException syntaxError (String message)
String toString ()
Static Public Member Functions
static int dehexchar (char c)
Private Attributes
long character
boolean eof
long index
long line
char previous
Reader reader
boolean usePrevious
Detailed Description
A JSONTokener takes a source string and extracts characters and tokens from it. It is used by the JSONObject and JSONArray constructors to parse JSON source strings.
Author
JSON.org
Version
2012-02-16
Definition at line 41 of file JSONTokener.java.
Constructor & Destructor Documentation
org.json.JSONTokener.JSONTokener (Reader reader)
Construct a JSONTokener from a Reader.
Parameters
reader A reader.
Definition at line 57 of file JSONTokener.java.
References org.json.JSONTokener.character, org.json.JSONTokener.eof, org.json.JSONTokener.index, org.json.JSONTokener.line, org.json.JSONTokener.previous, and org.json.JSONTokener.usePrevious.
                                      {
        this.reader = reader.markSupported()
            ? reader
            : new BufferedReader(reader);
        this.eof = false;
        this.usePrevious = false;
        this.previous = 0;
        this.index = 0;
        this.character = 1;
        this.line = 1;
    }
org.json.JSONTokener.JSONTokener (InputStream inputStream) throws JSONException
Construct a JSONTokener from an InputStream.
Definition at line 73 of file JSONTokener.java.
                                                                     {
        this(new InputStreamReader(inputStream));
    }
org.json.JSONTokener.JSONTokener (String s)
Construct a JSONTokener from a string.
Parameters
s A source string.
Definition at line 83 of file JSONTokener.java.
                                 {
        this(new StringReader(s));
    }
Member Function Documentation
void org.json.JSONTokener.back () throws JSONException
Back up one character. This provides a sort of lookahead capability, so that you can test for a digit or letter before attempting to parse the next number or identifier.
Definition at line 93 of file JSONTokener.java.
References org.json.JSONTokener.character, org.json.JSONTokener.eof, org.json.JSONTokener.index, and org.json.JSONTokener.usePrevious.
Referenced by org.json.JSONTokener.more(), org.json.XMLTokener.nextContent(), org.json.XMLTokener.nextMeta(), org.json.JSONTokener.nextTo(), org.json.XMLTokener.nextToken(), org.json.JSONTokener.nextValue(), and org.json.JSONTokener.skipTo().
                                            {
        if (this.usePrevious || this.index <= 0) {
            throw new JSONException("Stepping back two steps is not supported");
        }
        this.index -= 1;
        this.character -= 1;
        this.usePrevious = true;
        this.eof = false;
    }
static int org.json.JSONTokener.dehexchar (char c) [static]
Get the hex value of a character (base16).
Parameters
c A character between '0' and '9' or between 'A' and 'F' or between 'a' and 'f'.
Returns
An int between 0 and 15, or -1 if c was not a hex digit.
Definition at line 110 of file JSONTokener.java.
Referenced by org.json.Cookie.unescape().
                                        {
        if (c >= '0' && c <= '9') {
            return c - '0';
        }
        if (c >= 'A' && c <= 'F') {
            return c - ('A' - 10);
        }
        if (c >= 'a' && c <= 'f') {
            return c - ('a' - 10);
        }
        return -1;
    }
boolean org.json.JSONTokener.end ()
Definition at line 123 of file JSONTokener.java.
References org.json.JSONTokener.eof, and org.json.JSONTokener.usePrevious.
Referenced by org.json.JSONTokener.more(), org.json.JSONTokener.next(), and org.json.XMLTokener.nextCDATA().
                         {
        return this.eof && !this.usePrevious;
    }
boolean org.json.JSONTokener.more () throws JSONException
Determine if the source string still contains characters that next() can consume.
Returns
true if not yet at the end of the source.
Definition at line 133 of file JSONTokener.java.
References org.json.JSONTokener.back(), org.json.JSONTokener.end(), and org.json.JSONTokener.next().
Referenced by org.json.CookieList.toJSONObject(), org.json.HTTP.toJSONObject(), org.json.Cookie.toJSONObject(), and org.json.XML.toJSONObject().
                                               {
        this.next();
        if (this.end()) {
            return false;
        }
        this.back();
        return true;
    }
char org.json.JSONTokener.next () throws JSONException
Get the next character in the source string.
Returns
The next character, or 0 if past the end of the source string.
Definition at line 148 of file JSONTokener.java.
References org.json.JSONTokener.character, org.json.JSONTokener.eof, org.json.JSONTokener.index, org.json.JSONTokener.line, org.json.JSONTokener.previous, org.json.JSONTokener.reader, and org.json.JSONTokener.usePrevious.
Referenced by org.json.JSONTokener.more(), org.json.JSONTokener.next(), org.json.XMLTokener.nextCDATA(), org.json.JSONTokener.nextClean(), org.json.XMLTokener.nextContent(), org.json.XMLTokener.nextEntity(), org.json.XMLTokener.nextMeta(), org.json.JSONTokener.nextString(), org.json.JSONTokener.nextTo(), org.json.HTTPTokener.nextToken(), org.json.XMLTokener.nextToken(), org.json.JSONTokener.nextValue(), org.json.XMLTokener.skipPast(), org.json.JSONTokener.skipTo(), org.json.CookieList.toJSONObject(), org.json.HTTP.toJSONObject(), and org.json.Cookie.toJSONObject().
                                            {
        int c;
        if (this.usePrevious) {
            this.usePrevious = false;
            c = this.previous;
        } else {
            try {
                c = this.reader.read();
            } catch (IOException exception) {
                throw new JSONException(exception);
            }
            if (c <= 0) { // End of stream
                this.eof = true;
                c = 0;
            }
        }
        this.index += 1;
        if (this.previous == '\r') {
            this.line += 1;
            this.character = c == '\n' ? 0 : 1;
        } else if (c == '\n') {
            this.line += 1;
            this.character = 0;
        } else {
            this.character += 1;
        }
        this.previous = (char) c;
        return this.previous;
    }
char org.json.JSONTokener.next (char c) throws JSONException
Consume the next character, and check that it matches a specified character.
Parameters
c The character to match.
Returns
The character.
Exceptions
JSONException if the character does not match.
Definition at line 187 of file JSONTokener.java.
References org.json.JSONTokener.next(), and org.json.JSONTokener.syntaxError().
                                                  {
        char n = this.next();
        if (n != c) {
            throw this.syntaxError("Expected '" + c + "' and instead saw '" +
                    n + "'");
        }
        return n;
    }
String org.json.JSONTokener.next (int n) throws JSONException
Get the next n characters.
Parameters
n The number of characters to take.
Returns
A string of n characters.
Exceptions
JSONException Substring bounds error if there are not n characters remaining in the source string.
Definition at line 206 of file JSONTokener.java.
References org.json.JSONTokener.end(), org.json.JSONTokener.next(), and org.json.JSONTokener.syntaxError().
                                                    {
         if (n == 0) {
             return "";
         }
         char[] chars = new char[n];
         int pos = 0;
         while (pos < n) {
             chars[pos] = this.next();
             if (this.end()) {
                 throw this.syntaxError("Substring bounds error");
             }
             pos += 1;
         }
         return new String(chars);
     }
char org.json.JSONTokener.nextClean () throws JSONException
Get the next char in the string, skipping whitespace.
Exceptions
JSONException
Returns
A character, or 0 if there are no more characters.
Definition at line 230 of file JSONTokener.java.
References org.json.JSONTokener.next().
Referenced by org.json.JSONTokener.nextValue().
                                                 {
        for (;;) {
            char c = this.next();
            if (c == 0 || c > ' ') {
                return c;
            }
        }
    }
String org.json.JSONTokener.nextString (char quote) throws JSONException
Return the characters up to the next close quote character. Backslash processing is done. The formal JSON format does not allow strings in single quotes, but an implementation is allowed to accept them.
Parameters
quote The quoting character, either "
(double quote)
or '
(single quote)
.
Returns
A String.
Exceptions
JSONException Unterminated string.
Definition at line 251 of file JSONTokener.java.
References org.json.JSONTokener.next(), and org.json.JSONTokener.syntaxError().
Referenced by org.json.JSONTokener.nextValue().
                                                              {
        char c;
        StringBuffer sb = new StringBuffer();
        for (;;) {
            c = this.next();
            switch (c) {
            case 0:
            case '\n':
            case '\r':
                throw this.syntaxError("Unterminated string");
            case '\\':
                c = this.next();
                switch (c) {
                case 'b':
                    sb.append('\b');
                    break;
                case 't':
                    sb.append('\t');
                    break;
                case 'n':
                    sb.append('\n');
                    break;
                case 'f':
                    sb.append('\f');
                    break;
                case 'r':
                    sb.append('\r');
                    break;
                case 'u':
                    sb.append((char)Integer.parseInt(this.next(4), 16));
                    break;
                case '"':
                case '\'':
                case '\\':
                case '/':
                    sb.append(c);
                    break;
                default:
                    throw this.syntaxError("Illegal escape.");
                }
                break;
            default:
                if (c == quote) {
                    return sb.toString();
                }
                sb.append(c);
            }
        }
    }
String org.json.JSONTokener.nextTo (char delimiter) throws JSONException
Get the text up but not including the specified character or the end of line, whichever comes first.
Parameters
delimiter A delimiter character.
Returns
A string.
Definition at line 308 of file JSONTokener.java.
References org.json.JSONTokener.back(), and org.json.JSONTokener.next().
Referenced by org.json.CookieList.toJSONObject(), org.json.HTTP.toJSONObject(), and org.json.Cookie.toJSONObject().
                                                              {
        StringBuffer sb = new StringBuffer();
        for (;;) {
            char c = this.next();
            if (c == delimiter || c == 0 || c == '\n' || c == '\r') {
                if (c != 0) {
                    this.back();
                }
                return sb.toString().trim();
            }
            sb.append(c);
        }
    }
String org.json.JSONTokener.nextTo (String delimiters) throws JSONException
Get the text up but not including one of the specified delimiter characters or the end of line, whichever comes first.
Parameters
delimiters A set of delimiter characters.
Returns
A string, trimmed.
Definition at line 329 of file JSONTokener.java.
References org.json.JSONTokener.back(), and org.json.JSONTokener.next().
                                                                 {
        char c;
        StringBuffer sb = new StringBuffer();
        for (;;) {
            c = this.next();
            if (delimiters.indexOf(c) >= 0 || c == 0 ||
                    c == '\n' || c == '\r') {
                if (c != 0) {
                    this.back();
                }
                return sb.toString().trim();
            }
            sb.append(c);
        }
    }
Object org.json.JSONTokener.nextValue () throws JSONException
Get the next value. The value can be a Boolean, Double, Integer, JSONArray, JSONObject, Long, or String, or the JSONObject.NULL object.
Exceptions
JSONException If syntax error.
Returns
An object.
Definition at line 353 of file JSONTokener.java.
References org.json.JSONTokener.back(), org.json.JSONTokener.next(), org.json.JSONTokener.nextClean(), org.json.JSONTokener.nextString(), org.json.JSONObject.stringToValue(), and org.json.JSONTokener.syntaxError().
                                                   {
        char c = this.nextClean();
        String string;
        switch (c) {
            case '"':
            case '\'':
                return this.nextString(c);
            case '{':
                this.back();
                return new JSONObject(this);
            case '[':
                this.back();
                return new JSONArray(this);
        }
        /*
         * Handle unquoted text. This could be the values true, false, or
         * null, or it can be a number. An implementation (such as this one)
         * is allowed to also accept non-standard forms.
         *
         * Accumulate characters until we reach the end of the text or a
         * formatting character.
         */
        StringBuffer sb = new StringBuffer();
        while (c >= ' ' && ",:]}/\\\"[{;=#".indexOf(c) < 0) {
            sb.append(c);
            c = this.next();
        }
        this.back();
        string = sb.toString().trim();
        if ("".equals(string)) {
            throw this.syntaxError("Missing value");
        }
        return JSONObject.stringToValue(string);
    }
char org.json.JSONTokener.skipTo (char to) throws JSONException
Skip characters until the next character is the requested character. If the requested character is not found, no characters are skipped.
Parameters
to A character to skip to.
Returns
The requested character, or zero if the requested character is not found.
Definition at line 400 of file JSONTokener.java.
References org.json.JSONTokener.back(), org.json.JSONTokener.character, org.json.JSONTokener.index, org.json.JSONTokener.line, org.json.JSONTokener.next(), and org.json.JSONTokener.reader.
                                                     {
        char c;
        try {
            long startIndex = this.index;
            long startCharacter = this.character;
            long startLine = this.line;
            this.reader.mark(1000000);
            do {
                c = this.next();
                if (c == 0) {
                    this.reader.reset();
                    this.index = startIndex;
                    this.character = startCharacter;
                    this.line = startLine;
                    return c;
                }
            } while (c != to);
        } catch (IOException exc) {
            throw new JSONException(exc);
        }
        this.back();
        return c;
    }
JSONException org.json.JSONTokener.syntaxError (String message)
Make a JSONException to signal a syntax error.
Parameters
message The error message.
Returns
A JSONException object, suitable for throwing
Definition at line 432 of file JSONTokener.java.
References org.json.JSONTokener.toString().
Referenced by org.json.JSONTokener.next(), org.json.XMLTokener.nextCDATA(), org.json.XMLTokener.nextEntity(), org.json.XMLTokener.nextMeta(), org.json.JSONTokener.nextString(), org.json.HTTPTokener.nextToken(), org.json.XMLTokener.nextToken(), org.json.JSONTokener.nextValue(), and org.json.Cookie.toJSONObject().
                                                     {
        return new JSONException(message + this.toString());
    }
String org.json.JSONTokener.toString ()
Make a printable string of this JSONTokener.
Returns
` at {index} [character {character} line {line}]`
Definition at line 442 of file JSONTokener.java.
References org.json.JSONTokener.character, org.json.JSONTokener.index, and org.json.JSONTokener.line.
Referenced by org.json.JSONTokener.syntaxError().
                             {
        return " at " + this.index + " [character " + this.character + " line " +
            this.line + "]";
    }
Member Data Documentation
long org.json.JSONTokener.character [private]
Definition at line 43 of file JSONTokener.java.
Referenced by org.json.JSONTokener.back(), org.json.JSONTokener.JSONTokener(), org.json.JSONTokener.next(), org.json.JSONTokener.skipTo(), and org.json.JSONTokener.toString().
boolean org.json.JSONTokener.eof [private]
Definition at line 44 of file JSONTokener.java.
Referenced by org.json.JSONTokener.back(), org.json.JSONTokener.end(), org.json.JSONTokener.JSONTokener(), and org.json.JSONTokener.next().
long org.json.JSONTokener.index [private]
Definition at line 45 of file JSONTokener.java.
Referenced by org.json.JSONTokener.back(), org.json.JSONTokener.JSONTokener(), org.json.JSONTokener.next(), org.json.JSONTokener.skipTo(), and org.json.JSONTokener.toString().
long org.json.JSONTokener.line [private]
Definition at line 46 of file JSONTokener.java.
Referenced by org.json.JSONTokener.JSONTokener(), org.json.JSONTokener.next(), org.json.JSONTokener.skipTo(), and org.json.JSONTokener.toString().
char org.json.JSONTokener.previous [private]
Definition at line 47 of file JSONTokener.java.
Referenced by org.json.JSONTokener.JSONTokener(), and org.json.JSONTokener.next().
Reader org.json.JSONTokener.reader [private]
Definition at line 48 of file JSONTokener.java.
Referenced by org.json.JSONTokener.next(), and org.json.JSONTokener.skipTo().
boolean org.json.JSONTokener.usePrevious [private]
Definition at line 49 of file JSONTokener.java.
Referenced by org.json.JSONTokener.back(), org.json.JSONTokener.end(), org.json.JSONTokener.JSONTokener(), and org.json.JSONTokener.next().
The documentation for this class was generated from the following file:
org/json/JSONTokener.java