org.json.Cookie Class Reference
Static Public Member Functions
static String escape (String string)
static JSONObject toJSONObject (String string) throws JSONException
static String toString (JSONObject jo) throws JSONException
static String unescape (String string)
Detailed Description
Convert a web browser cookie specification to a JSONObject and back. JSON and Cookies are both notations for name/value pairs.
Author
JSON.org
Version
2010-12-24
Definition at line 33 of file Cookie.java.
Member Function Documentation
static String org.json.Cookie.escape (String string) [static]
Produce a copy of a string in which the characters '+', '', '=', ';' and control characters are replaced with `%hh`. This is a gentle form of URL encoding, attempting to cause as little distortion to the string as possible. The characters '=' and ';' are meta characters in cookies. By convention, they are escaped using the URL-encoding. This is only a convention, not a standard. Often, cookies are expected to have encoded values. We encode '=' and ';' because we must. We encode '' and '+' because they are meta characters in URL encoding.
Parameters
string The source string.
Returns
The escaped result.
Definition at line 47 of file Cookie.java.
Referenced by org.json.CookieList.toString(), and org.json.Cookie.toString().
                                               {
        char c;
        String s = string.trim();
        StringBuffer sb = new StringBuffer();
        int length = s.length();
        for (int i = 0; i < length; i += 1) {
            c = s.charAt(i);
            if (c < ' ' || c == '+' || c == '%' || c == '=' || c == ';') {
                sb.append('%');
                sb.append(Character.forDigit((char)((c >>> 4) & 0x0f), 16));
                sb.append(Character.forDigit((char)(c & 0x0f), 16));
            } else {
                sb.append(c);
            }
        }
        return sb.toString();
    }
static JSONObject org.json.Cookie.toJSONObject (String string) throws JSONException [static]
Convert a cookie specification string into a JSONObject. The string will contain a name value pair separated by '='. The name and the value will be unescaped, possibly converting '+' and '' sequences. The cookie properties may follow, separated by ';', also represented as name=value (except the secure property, which does not have a value). The name will be stored under the key `name`, and the value will be stored under the key `value`. This method does not do checking or validation of the parameters. It only converts the cookie string into a JSONObject.
Parameters
string The cookie specification string.
Returns
A JSONObject containing `name`, `value`, and possibly other members.
Exceptions
JSONException
Definition at line 81 of file Cookie.java.
References org.json.JSONTokener.more(), org.json.JSONTokener.next(), org.json.JSONTokener.nextTo(), org.json.JSONObject.put(), org.json.JSONTokener.syntaxError(), and org.json.Cookie.unescape().
                                                                              {
        String name;
        JSONObject jo = new JSONObject();
        Object value;
        JSONTokener x = new JSONTokener(string);
        jo.put("name", x.nextTo('='));
        x.next('=');
        jo.put("value", x.nextTo(';'));
        x.next();
        while (x.more()) {
            name = unescape(x.nextTo("=;"));
            if (x.next() != '=') {
                if (name.equals("secure")) {
                    value = Boolean.TRUE;
                } else {
                    throw x.syntaxError("Missing '=' in cookie parameter.");
                }
            } else {
                value = unescape(x.nextTo(';'));
                x.next();
            }
            jo.put(name, value);
        }
        return jo;
    }
static String org.json.Cookie.toString (JSONObject jo) throws JSONException [static]
Convert a JSONObject into a cookie specification string. The JSONObject must contain `name` and `value` members. If the JSONObject contains `expires`, `domain`, `path`, or `secure` members, they will be appended to the cookie specification string. All other members are ignored.
Parameters
jo A JSONObject
Returns
A cookie specification string
Exceptions
JSONException
Definition at line 118 of file Cookie.java.
References org.json.Cookie.escape().
                                                                      {
        StringBuffer sb = new StringBuffer();
        sb.append(escape(jo.getString("name")));
        sb.append("=");
        sb.append(escape(jo.getString("value")));
        if (jo.has("expires")) {
            sb.append(";expires=");
            sb.append(jo.getString("expires"));
        }
        if (jo.has("domain")) {
            sb.append(";domain=");
            sb.append(escape(jo.getString("domain")));
        }
        if (jo.has("path")) {
            sb.append(";path=");
            sb.append(escape(jo.getString("path")));
        }
        if (jo.optBoolean("secure")) {
            sb.append(";secure");
        }
        return sb.toString();
    }
static String org.json.Cookie.unescape (String string) [static]
Convert %hh sequences to single characters, and convert plus to space.
Parameters
string A string that may contain +
(plus)
and %hh sequences.
Returns
The unescaped string.
Definition at line 150 of file Cookie.java.
References org.json.JSONTokener.dehexchar().
Referenced by org.json.CookieList.toJSONObject(), and org.json.Cookie.toJSONObject().
                                                 {
        int length = string.length();
        StringBuffer sb = new StringBuffer();
        for (int i = 0; i < length; ++i) {
            char c = string.charAt(i);
            if (c == '+') {
                c = ' ';
            } else if (c == '%' && i + 2 < length) {
                int d = JSONTokener.dehexchar(string.charAt(i + 1));
                int e = JSONTokener.dehexchar(string.charAt(i + 2));
                if (d >= 0 && e >= 0) {
                    c = (char)(d * 16 + e);
                    i += 2;
                }
            }
            sb.append(c);
        }
        return sb.toString();
    }
The documentation for this class was generated from the following file:
org/json/Cookie.java