org.json.XML Class Reference
Static Public Member Functions
static String escape (String string)
static void noSpace (String string) throws JSONException
static Object stringToValue (String string)
static JSONObject toJSONObject (String string) throws JSONException
static String toString (Object object) throws JSONException
static String toString (Object object, String tagName) throws JSONException
Static Public Attributes
static final Character AMP = new Character('&')
static final Character APOS = new Character('\'')
static final Character BANG = new Character('!')
static final Character EQ = new Character('=')
static final Character GT = new Character('>')
static final Character LT = new Character('<')
static final Character QUEST = new Character('?')
static final Character QUOT = new Character('`')
static final Character SLASH = new Character('/')
Static Private Member Functions
static boolean parse (XMLTokener x, JSONObject context, String name) throws JSONException
Detailed Description
This provides static methods to convert an XML text into a JSONObject, and to covert a JSONObject into an XML text.
Author
JSON.org
Version
2012-10-26
Definition at line 36 of file XML.java.
Member Function Documentation
static String org.json.XML.escape (String string) [static]
Replace special characters with XML escapes:
&
(ampersand)
is replaced by &amp;
<
(less than)
is replaced by &lt;
>
(greater than)
is replaced by &gt;
"
(double quote)
is replaced by &quot;
Parameters
string The string to be escaped.
Returns
The escaped string.
Definition at line 76 of file XML.java.
Referenced by org.json.JSONML.toString(), and org.json.XML.toString().
                                               {
        StringBuffer sb = new StringBuffer();
        for (int i = 0, length = string.length(); i < length; i++) {
            char c = string.charAt(i);
            switch (c) {
            case '&':
                sb.append("&amp;");
                break;
            case '<':
                sb.append("&lt;");
                break;
            case '>':
                sb.append("&gt;");
                break;
            case '"':
                sb.append("&quot;");
                break;
            case '\'':
                sb.append("&apos;");
                break;
            default:
                sb.append(c);
            }
        }
        return sb.toString();
    }
static void org.json.XML.noSpace (String string) throws JSONException [static]
Throw an exception if the string contains whitespace. Whitespace is not allowed in tagNames and attributes.
Parameters
string
Exceptions
JSONException
Definition at line 109 of file XML.java.
Referenced by org.json.JSONML.toString().
                                                                   {
        int i, length = string.length();
        if (length == 0) {
            throw new JSONException("Empty string.");
        }
        for (i = 0; i < length; i += 1) {
            if (Character.isWhitespace(string.charAt(i))) {
                throw new JSONException("'" + string +
                        "' contains a space character.");
            }
        }
    }
static boolean org.json.XML.parse (XMLTokener x, JSONObject context, String name) throws JSONException [static], [private]
Scan the content following the named tag, attaching it to the context.
Parameters
x The XMLTokener containing the source string.
context The JSONObject that will include the new material.
name The tag name.
Returns
true if the close tag is processed.
Exceptions
JSONException
Definition at line 130 of file XML.java.
References org.json.JSONObject.accumulate(), org.json.XML.BANG, org.json.XML.EQ, org.json.XML.GT, org.json.JSONObject.length(), org.json.XML.LT, org.json.JSONObject.opt(), org.json.XML.QUEST, org.json.XML.SLASH, and org.json.XML.stringToValue().
Referenced by org.json.XML.toJSONObject().
                                                                   {
        char c;
        int i;
        JSONObject jsonobject = null;
        String string;
        String tagName;
        Object token;
// Test for and skip past these forms:
// <!-- ... -->
// <! ... >
// <![ ... ]]>
// <? ... ?>
// Report errors for these forms:
// <>
// <=
// <<
        token = x.nextToken();
// <!
        if (token == BANG) {
            c = x.next();
            if (c == '-') {
                if (x.next() == '-') {
                    x.skipPast("-->");
                    return false;
                }
                x.back();
            } else if (c == '[') {
                token = x.nextToken();
                if ("CDATA".equals(token)) {
                    if (x.next() == '[') {
                        string = x.nextCDATA();
                        if (string.length() > 0) {
                            context.accumulate("content", string);
                        }
                        return false;
                    }
                }
                throw x.syntaxError("Expected 'CDATA['");
            }
            i = 1;
            do {
                token = x.nextMeta();
                if (token == null) {
                    throw x.syntaxError("Missing '>' after '<!'.");
                } else if (token == LT) {
                    i += 1;
                } else if (token == GT) {
                    i -= 1;
                }
            } while (i > 0);
            return false;
        } else if (token == QUEST) {
// <?
            x.skipPast("?>");
            return false;
        } else if (token == SLASH) {
// Close tag </
            token = x.nextToken();
            if (name == null) {
                throw x.syntaxError("Mismatched close tag " + token);
            }
            if (!token.equals(name)) {
                throw x.syntaxError("Mismatched " + name + " and " + token);
            }
            if (x.nextToken() != GT) {
                throw x.syntaxError("Misshaped close tag");
            }
            return true;
        } else if (token instanceof Character) {
            throw x.syntaxError("Misshaped tag");
// Open tag <
        } else {
            tagName = (String)token;
            token = null;
            jsonobject = new JSONObject();
            for (;;) {
                if (token == null) {
                    token = x.nextToken();
                }
// attribute = value
                if (token instanceof String) {
                    string = (String)token;
                    token = x.nextToken();
                    if (token == EQ) {
                        token = x.nextToken();
                        if (!(token instanceof String)) {
                            throw x.syntaxError("Missing value");
                        }
                        jsonobject.accumulate(string,
                                XML.stringToValue((String)token));
                        token = null;
                    } else {
                        jsonobject.accumulate(string, "");
                    }
// Empty tag <.../>
                } else if (token == SLASH) {
                    if (x.nextToken() != GT) {
                        throw x.syntaxError("Misshaped tag");
                    }
                    if (jsonobject.length() > 0) {
                        context.accumulate(tagName, jsonobject);
                    } else {
                        context.accumulate(tagName, "");
                    }
                    return false;
// Content, between <...> and </...>
                } else if (token == GT) {
                    for (;;) {
                        token = x.nextContent();
                        if (token == null) {
                            if (tagName != null) {
                                throw x.syntaxError("Unclosed tag " + tagName);
                            }
                            return false;
                        } else if (token instanceof String) {
                            string = (String)token;
                            if (string.length() > 0) {
                                jsonobject.accumulate("content",
                                        XML.stringToValue(string));
                            }
// Nested element
                        } else if (token == LT) {
                            if (parse(x, jsonobject, tagName)) {
                                if (jsonobject.length() == 0) {
                                    context.accumulate(tagName, "");
                                } else if (jsonobject.length() == 1 &&
                                       jsonobject.opt("content") != null) {
                                    context.accumulate(tagName,
                                            jsonobject.opt("content"));
                                } else {
                                    context.accumulate(tagName, jsonobject);
                                }
                                return false;
                            }
                        }
                    }
                } else {
                    throw x.syntaxError("Misshaped tag");
                }
            }
        }
    }
static Object org.json.XML.stringToValue (String string) [static]
Try to convert a string into a number, boolean, or null. If the string can't be converted, return the string. This is much less ambitious than JSONObject.stringToValue, especially because it does not attempt to convert plus forms, octal forms, hex forms, or E forms lacking decimal points.
Parameters
string A String.
Returns
A simple JSON value.
Definition at line 303 of file XML.java.
References org.json.JSONObject.NULL.
Referenced by org.json.JSONML.parse(), and org.json.XML.parse().
                                                      {
        if ("".equals(string)) {
            return string;
        }
        if ("true".equalsIgnoreCase(string)) {
            return Boolean.TRUE;
        }
        if ("false".equalsIgnoreCase(string)) {
            return Boolean.FALSE;
        }
        if ("null".equalsIgnoreCase(string)) {
            return JSONObject.NULL;
        }
        if ("0".equals(string)) {
            return new Integer(0);
        }
// If it might be a number, try converting it. If that doesn't work,
// return the string.
        try {
            char initial = string.charAt(0);
            boolean negative = false;
            if (initial == '-') {
                initial = string.charAt(1);
                negative = true;
            }
            if (initial == '0' && string.charAt(negative ? 2 : 1) == '0') {
                return string;
            }
            if ((initial >= '0' && initial <= '9')) {
                if (string.indexOf('.') >= 0) {
                    return Double.valueOf(string);
                } else if (string.indexOf('e') < 0 && string.indexOf('E') < 0) {
                    Long myLong = new Long(string);
                    if (myLong.longValue() == myLong.intValue()) {
                        return new Integer(myLong.intValue());
                    } else {
                        return myLong;
                    }
                }
            }
        } catch (Exception ignore) {
        }
        return string;
    }
static JSONObject org.json.XML.toJSONObject (String string) throws JSONException [static]
Convert a well-formed (but not necessarily valid) XML string into a JSONObject. Some information may be lost in this transformation because JSON is a data format and XML is a document format. XML uses elements, attributes, and content text, while JSON uses unordered collections of name/value pairs and arrays of values. JSON does not does not like to distinguish between elements and attributes. Sequences of similar elements are represented as JSONArrays. Content text may be placed in a `content` member. Comments, prologs, DTDs, and <[ [ ]]> are ignored.
Parameters
string The source string.
Returns
A JSONObject containing the structured data from the XML string.
Exceptions
JSONException
Definition at line 365 of file XML.java.
References org.json.JSONTokener.more(), org.json.XML.parse(), and org.json.XMLTokener.skipPast().
                                                                              {
        JSONObject jo = new JSONObject();
        XMLTokener x = new XMLTokener(string);
        while (x.more() && x.skipPast("<")) {
            parse(x, jo, null);
        }
        return jo;
    }
static String org.json.XML.toString (Object object) throws JSONException [static]
Convert a JSONObject into a well-formed, element-normal XML string.
Parameters
object A JSONObject.
Returns
A string.
Exceptions
JSONException
Definition at line 381 of file XML.java.
Referenced by org.json.XML.toString().
                                                                      {
        return toString(object, null);
    }
static String org.json.XML.toString (Object object, String tagName) throws JSONException [static]
Convert a JSONObject into a well-formed, element-normal XML string.
Parameters
object A JSONObject.
tagName The optional name of the enclosing tag.
Returns
A string.
Exceptions
JSONException
Definition at line 393 of file XML.java.
References org.json.JSONObject.append(), org.json.XML.escape(), org.json.JSONArray.get(), org.json.JSONObject.keys(), org.json.JSONArray.length(), org.json.JSONArray.opt(), org.json.JSONObject.opt(), and org.json.XML.toString().
                                 {
        StringBuffer sb = new StringBuffer();
        int i;
        JSONArray ja;
        JSONObject jo;
        String key;
        Iterator keys;
        int length;
        String string;
        Object value;
        if (object instanceof JSONObject) {
// Emit <tagName>
            if (tagName != null) {
                sb.append('<');
                sb.append(tagName);
                sb.append('>');
            }
// Loop thru the keys.
            jo = (JSONObject)object;
            keys = jo.keys();
            while (keys.hasNext()) {
                key = keys.next().toString();
                value = jo.opt(key);
                if (value == null) {
                    value = "";
                }
                if (value instanceof String) {
                    string = (String)value;
                } else {
                    string = null;
                }
// Emit content in body
                if ("content".equals(key)) {
                    if (value instanceof JSONArray) {
                        ja = (JSONArray)value;
                        length = ja.length();
                        for (i = 0; i < length; i += 1) {
                            if (i > 0) {
                                sb.append('\n');
                            }
                            sb.append(escape(ja.get(i).toString()));
                        }
                    } else {
                        sb.append(escape(value.toString()));
                    }
// Emit an array of similar keys
                } else if (value instanceof JSONArray) {
                    ja = (JSONArray)value;
                    length = ja.length();
                    for (i = 0; i < length; i += 1) {
                        value = ja.get(i);
                        if (value instanceof JSONArray) {
                            sb.append('<');
                            sb.append(key);
                            sb.append('>');
                            sb.append(toString(value));
                            sb.append("</");
                            sb.append(key);
                            sb.append('>');
                        } else {
                            sb.append(toString(value, key));
                        }
                    }
                } else if ("".equals(value)) {
                    sb.append('<');
                    sb.append(key);
                    sb.append("/>");
// Emit a new tag <k>
                } else {
                    sb.append(toString(value, key));
                }
            }
            if (tagName != null) {
// Emit the </tagname> close tag
                sb.append("</");
                sb.append(tagName);
                sb.append('>');
            }
            return sb.toString();
// XML does not have good support for arrays. If an array appears in a place
// where XML is lacking, synthesize an <array> element.
        } else {
            if (object.getClass().isArray()) {
                object = new JSONArray(object);
            }
            if (object instanceof JSONArray) {
                ja = (JSONArray)object;
                length = ja.length();
                for (i = 0; i < length; i += 1) {
                    sb.append(toString(ja.opt(i), tagName == null ? "array" : tagName));
                }
                return sb.toString();
            } else {
                string = (object == null) ? "null" : escape(object.
      toString());
                return (tagName == null) ? "\"" + string + "\"" :
                    (string.length() == 0) ? "<" + tagName + "/>" :
                    "<" + tagName + ">" + string + "</" + tagName + ">";
            }
        }
    }
Member Data Documentation
final Character org.json.XML.AMP = new Character('&') [static]
The Character '&'.
Definition at line 39 of file XML.java.
final Character org.json.XML.APOS = new Character('\'') [static]
The Character '''.
Definition at line 42 of file XML.java.
final Character org.json.XML.BANG = new Character('!') [static]
The Character '!'.
Definition at line 45 of file XML.java.
Referenced by org.json.XMLTokener.nextMeta(), org.json.XMLTokener.nextToken(), org.json.JSONML.parse(), and org.json.XML.parse().
final Character org.json.XML.EQ = new Character('=') [static]
The Character '='.
Definition at line 48 of file XML.java.
Referenced by org.json.XMLTokener.nextMeta(), org.json.XMLTokener.nextToken(), org.json.JSONML.parse(), and org.json.XML.parse().
final Character org.json.XML.GT = new Character('>') [static]
The Character '>'.
Definition at line 51 of file XML.java.
Referenced by org.json.XMLTokener.nextMeta(), org.json.XMLTokener.nextToken(), org.json.JSONML.parse(), and org.json.XML.parse().
final Character org.json.XML.LT = new Character('<') [static]
The Character '<'.
Definition at line 54 of file XML.java.
Referenced by org.json.XMLTokener.nextContent(), org.json.XMLTokener.nextMeta(), org.json.JSONML.parse(), and org.json.XML.parse().
final Character org.json.XML.QUEST = new Character('?') [static]
The Character '?'.
Definition at line 57 of file XML.java.
Referenced by org.json.XMLTokener.nextMeta(), org.json.XMLTokener.nextToken(), org.json.JSONML.parse(), and org.json.XML.parse().
final Character org.json.XML.QUOT = new Character('`') [static]
The Character '`'.
Definition at line 60 of file XML.java.
final Character org.json.XML.SLASH = new Character('/') [static]
The Character '/'.
Definition at line 63 of file XML.java.
Referenced by org.json.XMLTokener.nextMeta(), org.json.XMLTokener.nextToken(), org.json.JSONML.parse(), and org.json.XML.parse().
The documentation for this class was generated from the following file:
org/json/XML.java