org.json.CookieList Class Reference
Static Public Member Functions
static JSONObject toJSONObject (String string) throws JSONException
static String toString (JSONObject jo) throws JSONException
Detailed Description
Convert a web browser cookie list string to a JSONObject and back.
Author
JSON.org
Version
2010-12-24
Definition at line 34 of file CookieList.java.
Member Function Documentation
static JSONObject org.json.CookieList.toJSONObject (String string) throws JSONException [static]
Convert a cookie list into a JSONObject. A cookie list is a sequence of name/value pairs. The names are separated from the values by '='. The pairs are separated by ';'. The names and the values will be unescaped, possibly converting '+' and '' sequences.
To add a cookie to a cooklist, cookielistJSONObject.put(cookieJSONObject.getString(`name`), cookieJSONObject.getString(`value`));
Parameters
string A cookie list string
Returns
A JSONObject
Exceptions
JSONException
Definition at line 49 of file CookieList.java.
References org.json.JSONTokener.more(), org.json.JSONTokener.next(), org.json.JSONTokener.nextTo(), org.json.JSONObject.put(), and org.json.Cookie.unescape().
                                                                              {
        JSONObject jo = new JSONObject();
        JSONTokener x = new JSONTokener(string);
        while (x.more()) {
            String name = Cookie.unescape(x.nextTo('='));
            x.next('=');
            jo.put(name, Cookie.unescape(x.nextTo(';')));
            x.next();
        }
        return jo;
    }
static String org.json.CookieList.toString (JSONObject jo) throws JSONException [static]
Convert a JSONObject into a cookie list. A cookie list is a sequence of name/value pairs. The names are separated from the values by '='. The pairs are separated by ';'. The characters '', '+', '=', and ';' in the names and values are replaced by `%hh`.
Parameters
jo A JSONObject
Returns
A cookie list string
Exceptions
JSONException
Definition at line 71 of file CookieList.java.
References org.json.Cookie.escape().
                                                                      {
        boolean b = false;
        Iterator keys = jo.keys();
        String string;
        StringBuffer sb = new StringBuffer();
        while (keys.hasNext()) {
            string = keys.next().toString();
            if (!jo.isNull(string)) {
                if (b) {
                    sb.append(';');
                }
                sb.append(Cookie.escape(string));
                sb.append("=");
                sb.append(Cookie.escape(jo.getString(string)));
                b = true;
            }
        }
        return sb.toString();
    }
The documentation for this class was generated from the following file:
org/json/CookieList.java